### ISSUE TITLE
Extruder Clearance Input filed broken

### ISSUE THREAD

**Issue by tome9111991** [SoftFever/OrcaSlicer#1014]
Hi,
after switch from english to german language the text input fied is broken from Extruder Clearance.
in german version slide down the field 2 lines.
![german](https://user-images.githubusercontent.com/57866234/237044208-4b0bcec9-86af-4041-9bb8-cb030b0a9146.png)

after switch back to english vesion  slide down the field 1 lines.
![Screenshot 2023-05-09 104328](https://user-images.githubusercontent.com/57866234/237044335-be41ee95-c85e-48bb-ba26-3d3bec1584f2.png)

Radius should be 65mm
Heigh to Rot = 36mm

Printer Voron 2.3 300

Issue only on 1.6.3 beta i dont know what build i use.
Win10

Workaround to fix input filed:
Switch Printer
exp.
from User presets to system presets and back to the  User presets the input field is correct.

**Comment by tome9111991** [comment]
i tried this build https://github.com/SoftFever/OrcaSlicer/actions/runs/4925890271
still same issue

**Comment by hliebscher** [comment]
is fixed with #1012 
![fiexed](https://github.com/SoftFever/OrcaSlicer/assets/9274162/b03ddc77-4f70-4c98-b7a0-186997efb79c)

**Comment by tome9111991** [comment]
sorry i tried some build but still issue.
i can change language from german to english still have this bug

**Comment by hliebscher** [comment]
i can change any language

**Comment by tome9111991** [comment]
i have this issue still in 1.6.3 pre-release

**Comment by SoftFever** [comment]
Maybe a Graphic Driver issue.
Have you tried to update the GPU driver?

**Comment by tome9111991** [comment]
Yes i have tried latest driver and default driver from windows10
