### ISSUE TITLE
Crash when switching to the Device tab of a Klipper printer

### ISSUE THREAD

**Issue by darkhog** [SoftFever/OrcaSlicer#10756]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1 Beta

### Operating System (OS)

Linux

### OS Version

OpenSuSE Tumbleweed

### Additional system information

I am using flatpak x86_64 version of Orca.

### Printer

Elegoo Neptune 4 Plus

### How to reproduce

1. Connect the printer over wifi (unsure if wifi part is important)
2. Set up connection in Orca
3. Switch to the Klipper interface by going to the device tab.

### Actual results

It crashes.

### Expected results

No crash.

### Project file & Debug log uploads

It happens regardless of regardless of project, so no zip necessary.
Log: 

[debug_Tue_Sep_16_10_39_29_2.log](https://github.com/user-attachments/files/22359280/debug_Tue_Sep_16_10_39_29_2.log)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Anything else?

It's a step up from 2.3.0 stable, where the Orca would simply crash when attempting to connect to the printer (without clicking the device tab), then on any subsequent boots until the entire config is cleared. Actually, this is the only reason why I've updated to 2.3.1 beta, as I don't tend to run beta software normally.

It's also a minor issue, sending print over wifi works just fine, it's just the device tab that crashes the program and I can load Klipper gui in my browser anyway. Annoying bug, but easy to avoid.

**Comment by igoransuper** [comment]
i have the same problem on my Ubuntu 24 . Printer - Qidi Q2

**Comment by CuddlyKraken** [comment]
Just came to report the same lol. 
Cosmic Pop-os
E3 S1 Pro running Klipper.

**Comment by VoloshynArtem** [comment]
I've encountered a similar issue with OrcaSlicer crashing when connecting to the printer when I first switched from OctoPrint to Mainsail+Moonraker. 
My temporary workaround was to add Moonraker's port (which should be _7125_ by default, if I remember correctly) to the connection configuration. 

That said, this may not be helpful to you, as uploading G-code from the slicer works fine, and Moonraker's web interface doesn't provide any useful settings or information (it might not even exist on tightly integrated printers), aside from preventing your slicer from crashing when selecting the device tab.

Also, if you find yourself inside a constant crash cycle again, I found that disconnecting/unplugging from your network makes OrcaSlicer start normally, allowing access to your configuration without the need to manually look for and modify the config files.

**Comment by darkhog** [comment]
Well, it's a brand new printer and it uses fluidd interface.

**Comment by Xavier06fr** [comment]
Same issue here on Fedora using appimage beta version

**Comment by PeterTucker** [comment]
+1 for me. Fedora Flatpak beta

**Comment by Ziomal12** [comment]
Same here with Fedora flatpak beta and Klipper printer

**Comment by Aergernis** [comment]
Same for me. Tried with AppImage, Flatpack and building.

[debug_Sat_Sep_20_16_55_14_42493.log](https://github.com/user-attachments/files/22442601/debug_Sat_Sep_20_16_55_14_42493.log)
[sh log.txt](https://github.com/user-attachments/files/22442602/sh.log.txt)

**Comment by PeterTucker** [comment]
For anyone looking for a temporary solution, I went with the docker build:
https://github.com/linuxserver/docker-orcaslicer

**Comment by robotfishe** [comment]
I'm running 2.3.0 on NixOS and have the same issue @darkhog mentioned - OrcaSlicer crashes when a device URL is added to the settings. I'm also using Fluidd - is that the same for everyone in the thread? Might help the devs narrow down the issue if we can confirm it's interface-specific.

**Comment by darkhog** [comment]
I'm using Elegoo Neptune 4 Plus which uses fluidd as its interface. If you install beta, it's more or less stable (aside of the device tab thing, of course) and you should be able to at least send print jobs over LAN, just be careful to not click device tab accidentally.

**Comment by robotfishe** [comment]
I've done a bit more tinkering with this today and found a workaround for anyone stuck on the non-beta release: if you set your OrcaSlicer to connect directly to Moonraker it won't crash, and you'll be able to upload gcode files - you'll just have to use an external browser to access the Fluidd UI, same as those who are on 2.3.1 beta currently need to.

All you need to do to change that setting without resetting OrcaSlicer to default is open your .config/OrcaSlicer/user/default/machine/**printer**.json file, and add ":7125" to the "print_host" setting. (That's assuming you haven't changed the Moonraker port from the default on your setup of course.)

EDIT: I just noticed [VoloshynArtem](https://github.com/VoloshynArtem) recommended exactly the same thing (head-wall-emoji)

Meanwhile, I'll upload a backtrace file here for the crashes I was experiencing in case that's of use to the devs in figuring out how to get us full UI access on linux again:

[orcaslicer_backtrace_1.txt](https://github.com/user-attachments/files/22537335/orcaslicer_backtrace_1.txt)

**Comment by Salty4life** [comment]
Very much still an issue that breaks workflow on OrcaSlicer
I'm using NixOS and I'm on version `2.3.2 - Dev` (the latest beta as far as I know)

Bellow is the debug log where I basically just open OrcaSlicer and click the device tab:

[debug_Tue_Oct_14_23_03_59_71442.log.txt](https://github.com/user-attachments/files/22914112/debug_Tue_Oct_14_23_03_59_71442.log.txt)

**Comment by aweber1234** [comment]
Same issue using AppImage on debian KDE.

**Comment by eras** [comment]
This looks like the same issue as #7210, which looks like it's a bug in webkit. 

Someone also reported that having self-compiled it it worked fine, but it is unknown which version of e.g. webkit that build was using.

**Comment by y-e-r** [comment]
having this same issue with Fedora, KDE, Intel Arc A770, latest flatpak of orca slicer
device tab starts to load, shows fluidd logo and 'klippy not connected'
then orca crashes

**Comment by szafranski** [comment]
still present. Bazzite KDE. checked main and last stable

**Comment by Meltedgyro** [comment]
issue still present, connecting to qidi q1 pro on fedora installed from flatpak. software crashes and raises error with webkit web process crashed.

**Comment by Git-Ultravo** [comment]
Same as mentioned above, issue still present. Bazzite KDE.

**Comment by JSH32** [comment]
Happening on fedora with appimage

**Comment by t3kkm0tt** [comment]
Happening on hyprland on arch on stable version

**Comment by gkouros50** [comment]
Still happening on Ubuntu 24.04 stable release both app-image and flatpak

**Comment by szafranski** [comment]
It stopped for me after moving to AMD GPU Not saying that should be the
solution, just mentioning

wt., 25 lis 2025 o 05:02 CuriosKouros ***@***.***> napisał(a):

**Comment by AByzhynar** [comment]
Date: 25 Nov 2025
Env:  Ubuntu 24.04, Kernel 6.8.0-88-generic
App Version: 2.3.1 Stable
App type: AppImage

Still crashing every time when switching to "Device" tab.

**Comment by sunsoy** [comment]
+1
Pop!_OS 22.04 , 6.17.4-76061704-generic
OrcaSlicer-2.3.1

**Comment by junderw52** [comment]
+1
CachyOS, 6.17.9-2-cachyos
OrcaSlicer 2.3.1
Flatpak

**Comment by TraineePilotLeo** [comment]
+1
Cachy OS 6.17.9-2 64 bit
Wayland
Flatpak
KDE Nvidia GPU

**Comment by gkouros50** [comment]
> It stopped for me after moving to AMD GPU Not saying that should be the
> solution, just mentioning
> 
> wt., 25 lis 2025 o 05:02 CuriosKouros ***@***.***> napisał(a):
> […](#)

Can confirm when I removed my NVIDIA 4070 and used my AMD APU It worked. How could we go about forcing Orca to launch with an IGPU?

**Comment by szafranski** [comment]
Or at least software rendering could be optional

**Comment by webbwerkx** [comment]
Its weird. I have 3 pcs. 2 with single monitors. One with 2 monitors. I have exact same configs on all as they as all symlinked via stow. The one with dual monitors will freeze up as soon as I add my ip and switch to device tab, it loads and freezes. Works fine on other pcs, all installed with yay -S orca-slicer-bin. Ive tried fresh installs of drivers and everything, running orca in x11 and everything but nothing works!

**Comment by webbwerkx** [comment]
Same thing with Prusa-Slicer....Might be a Klipper issue, not Orca

**Comment by darkhog** [comment]
> Same thing with Prusa-Slicer....Might be a Klipper issue, not Orca

I'd agree... if the very same interface didn't work in a run-of-the-mill webbrowser.

**Comment by webbwerkx** [comment]
Yeah it works via browser......Hope they fix this soon! @darkhog

**Comment by darkhog** [comment]
Also isn't PrusaSlicer a fork of Orca? So any issues present in Orca would be also present in it, unless actually fixed by Prusa team?

**Comment by robotfishe** [comment]
> Also isn't PrusaSlicer a fork of Orca? So any issues present in Orca would be also present in it, unless actually fixed by Prusa team?

Other way around - Orca is downstream from Prusa.

Looks like there was some discussion of a similar issue on the Prusaslicer github, but no updates since August and no indication that it's been fixed: https://github.com/prusa3d/PrusaSlicer/issues/13835

**Comment by gkouros50** [comment]
I have done the stupid and purchased a radeon 9070XT, out of curiosity. OrcaSlicer run perfectly fine now. no issues using the device tab with my SOVOL sv08s mainsail interface on dual monitors.

**Comment by darkhog** [comment]
That shouldn't be the fix at all. Also, there were people with AMD hardware that had the same issue on both PrusaSlicer and here. Also, isn't the Device tab supposed to be a simple Chromium webview? Other CEF/Electron-based apps such as Spotify or Discord do not have such crashes, so why Orca/Prusa does?

**Comment by t3kkm0tt** [comment]
Im gonna try to install nouveau and see if it helps

**Comment by webbwerkx** [comment]
I did my weekly update last night and device tab is now working. Installed with orca-slicer-bin, not using flat pack

**Comment by t3kkm0tt** [comment]
Oh ok nice

**Comment by erviker** [comment]
just an observation fluiid crashes my orca-slicer. but not mainsail.

**Comment by darkhog** [comment]
> just an observation fluiid crashes my orca-slicer. but not mainsail.

Interesting. Is there any difference in handling the device tab between mainsail devices and fluidd?

**Comment by TheRealGramdalf** [comment]
The root issue was fixed in mainsail v2.16.1 (or higher), see https://github.com/OrcaSlicer/OrcaSlicer/issues/7210#issuecomment-3678163872.

**Comment by timnolte** [comment]
Just reporting that this is now an issue with at least the latest 2.3.2-dev nightly, crashing when trying to access a Klipper/Fluidd printer. My earlier nightly of 2.3.2-dev had no problems.

OrcaSlicer Version: 2.3.2-dev
```
commit e025860b2c11476a353c7441571852c8b3a54b18
Refs: [main], {origin/main}, {origin/HEAD}, nightly-builds-2955-ge025860b2c
Author:     Azi <azio@pantheondesign.ca>
AuthorDate: Fri Feb 6 07:02:48 2026 -0800
Commit:     GitHub <noreply@github.com>
CommitDate: Fri Feb 6 23:02:48 2026 +0800
```

Fluidd Version: v1.36.2

**Comment by timnolte** [comment]
> Just reporting that this is now an issue with at least the latest 2.3.2-dev nightly, crashing when trying to access a Klipper/Fluidd printer. My earlier nightly of 2.3.2-dev had no problems.
> 
> OrcaSlicer Version: 2.3.2-dev
> 
> ```
> commit e025860b2c11476a353c7441571852c8b3a54b18
> Refs: [main], {origin/main}, {origin/HEAD}, nightly-builds-2955-ge025860b2c
> Author:     Azi <azio@pantheondesign.ca>
> AuthorDate: Fri Feb 6 07:02:48 2026 -0800
> Commit:     GitHub <noreply@github.com>
> CommitDate: Fri Feb 6 23:02:48 2026 +0800
> ```
> 
> Fluidd Version: v1.36.2

Just noting that this is not exclusive to Fluidd after all. When I switch the Devices tab to use Mainsail(v2.14.1) it also crashed.

**Comment by TheRealGramdalf** [comment]
> > Just reporting that this is now an issue with at least the latest 2.3.2-dev nightly, crashing when trying to access a Klipper/Fluidd printer. My earlier nightly of 2.3.2-dev had no problems.
> > 
> > OrcaSlicer Version: 2.3.2-dev
> > 
> > ```
> > commit e025860b2c11476a353c7441571852c8b3a54b18
> > Refs: [main], {origin/main}, {origin/HEAD}, nightly-builds-2955-ge025860b2c
> > Author:     Azi <azio@pantheondesign.ca>
> > AuthorDate: Fri Feb 6 07:02:48 2026 -0800
> > Commit:     GitHub <noreply@github.com>
> > CommitDate: Fri Feb 6 23:02:48 2026 +0800
> > ```
> > 
> > Fluidd Version: v1.36.2
> 
> Just noting that this is not exclusive to Fluidd after all. When I switch the Devices tab to use Mainsail(v2.14.1) it also crashed.

https://github.com/OrcaSlicer/OrcaSlicer/issues/10756#issuecomment-3803162657

**Comment by timnolte** [comment]
> > > Just reporting that this is now an issue with at least the latest 2.3.2-dev nightly, crashing when trying to access a Klipper/Fluidd printer. My earlier nightly of 2.3.2-dev had no problems.
> > > 
> > > OrcaSlicer Version: 2.3.2-dev
> > > 
> > > ```
> > > commit e025860b2c11476a353c7441571852c8b3a54b18
> > > Refs: [main], {origin/main}, {origin/HEAD}, nightly-builds-2955-ge025860b2c
> > > Author:     Azi <azio@pantheondesign.ca>
> > > AuthorDate: Fri Feb 6 07:02:48 2026 -0800
> > > Commit:     GitHub <noreply@github.com>
> > > CommitDate: Fri Feb 6 23:02:48 2026 +0800
> > > ```
> > > 
> > > Fluidd Version: v1.36.2
> > 
> > Just noting that this is not exclusive to Fluidd after all. When I switch the Devices tab to use Mainsail(v2.14.1) it also crashed.
> 
> https://github.com/OrcaSlicer/OrcaSlicer/issues/10756#issuecomment-3803162657

@TheRealGramdalf the very fact that this was working in older versions of OrcaSlicer is proof that this is not a Fluid/Mainsail issue at it's core. My printer doesn't have any new updates for either of those so that is not a fix. Also the version I'm using of both of those work just fine with the latest version of the Chrome browser so this is further indication of a bad OrcaSlicer change.

**Comment by IntenseWiggling** [comment]
The crash is happening in webkit at [/Source/WebKit/UIProcess/gtk/AcceleratedBackingStore.cpp:754](https://github.com/WebKit/WebKit/blob/wpewebkit-2.50.5/Source/WebKit/UIProcess/gtk/AcceleratedBackingStore.cpp#L754) due to a nullptr reference.

```gdb
Thread 1 "orcaslicer_main" received signal SIGSEGV, Segmentation fault.
WebKit::AcceleratedBackingStore::update (this=0x0, context=...)
    at /usr/src/debug/webkit2gtk-4.1/webkitgtk-2.50.5/Source/WebKit/UIProcess/gtk/AcceleratedBackingStore.cpp:754
754         if (m_surfaceID == context.contextID)
(gdb) disp this
1: this = (WebKit::AcceleratedBackingStore *) 0x0
```

Appears to be this reported bug in webkit: [ Browser (GTK3/4) entering accelerated mode even if HW acceleration is disabled when browsing web pages with css-view-transtion ](https://bugs.webkit.org/show_bug.cgi?id=304067) as the same underlying issue.  If I replace the device url in orcaslicer with that of the [sample page on that bug report](https://wpt.live/css/css-view-transitions/auto-name.html) and then switch to the device tab, the crash happens in exactly the same way. It's something else in fluidd that's triggering it, but it's the same result.

The crash can be avoided if you set [ZINK_DISABLE_OVERRIDE=1](https://github.com/OrcaSlicer/OrcaSlicer/blob/cf31d05d26c0f55c4e56264a0229e2b705dcc974/src/dev-utils/platform/unix/build_linux_image.sh.in#L60), but that [will lead to other issues](https://github.com/OrcaSlicer/OrcaSlicer/pull/8373) (such as the build plate / preview rendering running like crap).

**Comment by IntenseWiggling** [comment]
Also, bambu-studio has this exact same problem (when they have the zink workaround applied for nvidia).

```gdb
Thread 1 "bambustu_main" received signal SIGSEGV, Segmentation fault.
WebKit::AcceleratedBackingStore::update (this=0x0, context=...) at /usr/src/debug/webkit2gtk/webkitgtk-2.50.5/Source/WebKit/UIProcess/gtk/AcceleratedBackingStore.cpp:754
754	    if (m_surfaceID == context.contextID)
(gdb) disp this
1: this = (WebKit::AcceleratedBackingStore *) 0x0
```

It's actually more annoying because they seem to pre-load the device tab, so it crashes before even selecting it.

This is also a problem with prusa-slicer.

```gdb
Thread 1 "slic3r_main" received signal SIGSEGV, Segmentation fault.
WebKit::AcceleratedBackingStore::update (this=0x0, context=...)
    at /usr/src/debug/webkit2gtk-4.1/webkitgtk-2.50.5/Source/WebKit/UIProcess/gtk/AcceleratedBackingStore.cpp:754
754	    if (m_surfaceID == context.contextID)
(gdb) disp this
1: this = (WebKit::AcceleratedBackingStore *) 0x0
```

PrusaSlicer has a couple bug reports for the issue: [14999](https://github.com/prusa3d/PrusaSlicer/issues/14999) [13835](https://github.com/prusa3d/PrusaSlicer/issues/13835). There users note that `WEBKIT_DISABLE_COMPOSITING_MODE=0 WEBKIT_DISABLE_DMABUF_RENDERER=0 ` fixes it. For me, it just results in a different type of crash of prusa-slicer. It 'fixes' orca-slicer in the same way I noted before; disables hardware acceleration for rendering so it runs like crap.

**Comment by firepower9966** [comment]
Also changed network plugin from legacy to latest.
still crashes

**Comment by barankorkmaz91** [comment]
I'm on Mint 22.3 6.17.0-14-generic kernel. I'm using Orca Slicer 2.3.1 flatpak version. 

I was having the same connection problem with my Creality CR10-SE printer. Whenever I try to connect to Mainsail ip Orca was crashing. I've just downloaded Creality Prints latest version to check some settings for my printer and I've checked if the connection problem also happening on Creality Print but no I was able to connect from the device tab. 

After this I've also opened Orca Slicer again and try the device tab to see if it connects as well and to my suprise I can connect to my printer from the device tab without crashing. 

I don't know what happened but probably some package that came with the CP solved the issue. I hope it helps someone.

**Comment by firepower9966** [comment]
Also crashes using ORCaSlicer_Linux_AppImage_Ubuntu2404_V2.3.2-RC

**Comment by the3dfox** [comment]
Same for me, 
System:
  Kernel: 6.8.0-90-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: hpet
  Desktop: Cinnamon v: 6.4.8 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 vt: 7 dm: 1: GDM3 v: 46.2
    2: LightDM v: 1.30.0 Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble

Orca Slicer Version 2.3.1

**Comment by the3dfox** [comment]
updating mainsail to v2.17.0 solved the issue

**Comment by firepower9966** [comment]
Still crashes using 
mainsail
v2.17.0

**Comment by firepower9966** [comment]
I will check what version is installed and will try updating libwebkit2gtk-4.1.so.0 with https://www.ubuntuupdates.org/package/core/jammy/universe/security/libwebkit2gtk-4.1-0

**Comment by firepower9966** [comment]
Package is already installed.

**Comment by firepower9966** [comment]
running from terminal these are the errors:

[ORCaSlicer_Linux_AppImage_Ubuntu2404_V2.3.2-RC.txt](https://github.com/user-attachments/files/25736443/ORCaSlicer_Linux_AppImage_Ubuntu2404_V2.3.2-RC.txt)

crashes after a few seconds of displaying device screen with no klippy connection.

**Comment by firepower9966** [comment]
compare with 

[OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.1.txt](https://github.com/user-attachments/files/25736375/OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.1.txt)

this does not crash, device screen works normal and program needs to be close as normal.

**Comment by firepower9966** [comment]
OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.2-rc2 also crashes

**Comment by firepower9966** [comment]
run from terminal.

firepower@COLORFUL-CNV-B650M:~/App$ ./OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.2-rc2.AppImage
Segmentation fault (core dumped)

**Comment by firepower9966** [comment]
If I add port to IP address of printer 
:4409 for mainsail it works.
:4408 for fluid it crashes.

**Comment by samin50** [comment]
Updating using KIAUH on my printer (I now have Mainsail 2.17.0, Klipper 0.13.0-572, Moonraker 0.10-10), I can now go to the device tab in Orca and it doesn't crash anymore - although the performance is poor for me, which is discussed in another issue #12587.

**Comment by haydensoliver** [comment]
I replicated the issue on both the 2.3.2-rc2 flatpak and appimage installations, and found the same crashing behavior to occur when accessing the Devices tab. I was able to resolve the crashing issue and regain complete control of my Mainsail/Moonraker printer via the devices tab by performing a full system update on my printer and updating klipper on the machine.

I know this does not resolve the bug, but it is at least a workaround.

**Comment by timnolte** [comment]
It's rather disappointing that for some of us this means that we're are just out of luck unless there is an update for our printers, which may never happen. This seems like a pretty big failure for OrcaSlicer where it basically means loss of functionality for older printers. At least we can still use a real web browser, which is also a bit strange that a real browser will work but OrcaSlicer won't.

**Comment by barankorkmaz91** [comment]
I've installed Creality Print flatpak and now I can reach to device tab in Orca as well. I also updated the moonraker on my CR 10 SE device. I don't have any crashes since. I'm not sure if it is related but I was having this device tab crash for 1.5 years until I installed and ran Creality Print. Flatpak image is containerized it shouldn't affect this problem with Orca but I don't know.

**Comment by IntenseWiggling** [comment]
Oh interesting, I noticed it's now working for me under an Arch distrobox container,  from the AUR packages, when `WEBKIT_DISABLE_COMPOSITING_MODE=0` is set. Just need to be sure to run the binary directly and not the wrapper script at `/usr/bin/orca-slicer` (since the script sets `WEBKIT_DISABLE_COMPOSITING_MODE=1` with the ZINK stuff).

Plate/preview are running accelerated, and I can access Fluidd through the device tab without the crash.  Nvidia drivers 595.45.04.  

Tested running the AppImage binaries (--appimage-extract) in a bunch of other distros through distrobox, and they all work fine. But then the AppImage (directly or extracted) and flatpak don't work outside the containers in the host os (Bazzite).

Not sure what's going on there.

**Comment by IntenseWiggling** [comment]
OK so I can get it working using the straight AppImage and flatpak now.

Using the AppImage I need to set a few env variables. 

```sh
export WEBKIT_DISABLE_COMPOSITING_MODE=0
export ZINK_DISABLE_OVERRIDE=1
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json 
./orcaslicer.appimage
```

Easier to manage if using something like Gear Lever to manage your AppImages

Using the Flatpak, I need to override a few variables and then run the flatpak with the app binary directly instead of the entrypoint script.

```sh
❯ flatpak override --user --show com.orcaslicer.OrcaSlicer 
[Environment]
WEBKIT_DISABLE_COMPOSITING_MODE=0
__EGL_VENDOR_LIBRARY_FILENAMES=/usr/lib/x86_64-linux-gnu/GL/glvnd/egl_vendor.d/50_mesa.json
```

```sh
❯ flatpak run --command=/app/bin/orca-slicer com.orcaslicer.OrcaSlicer
```

I still don't get why this makes it work.

**Comment by domino-pl** [comment]
> export WEBKIT_DISABLE_COMPOSITING_MODE=0
> export ZINK_DISABLE_OVERRIDE=1
> export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json 
> ./orcaslicer.appimage

Didn't help for me with 2.3.2 tried with AppImage (and extracted app image).

**Comment by plozwick** [comment]
You are a hero!
Setting `WEBKIT_DISABLE_COMPOSITING_MODE=0` was all that's needed to get it working with the Qidi Q2.
Using AppImage v2.3.2 with Gear Lever on Arch Linux.

**Comment by darkhog** [comment]
> You are a hero! Setting `WEBKIT_DISABLE_COMPOSITING_MODE=0` was all that's needed to get it working with the Qidi Q2. Using AppImage v2.3.2 with Gear Lever on Arch Linux.

Interesting. If there's a way to bake that into the future release so it always sets it by default, that would be an acceptable fix. Might affect performance a little bit, but in a slicer that isn't too important.

**Comment by TheRealGramdalf** [comment]
Would it be feasible to add a settings option for these instead of relying on environment variables? How ENV vars are set/enforced vary depending on the packaging method, and hwaccel/rendering options are rarely a one size fits all setting. I'm not sure if such a setting is an option due to potential technical limitations, but it would be worth investigating.

**Comment by mimorational** [comment]
I confirm, WEBKIT_DISABLE_COMPOSITING_MODE=0   worked  on Bazzite 6.17.7-ba28.fc43.x86_64

**Comment by rasaolbr** [comment]
> export WEBKIT_DISABLE_COMPOSITING_MODE=0
> export ZINK_DISABLE_OVERRIDE=1
> export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json 
> ./orcaslicer.appimage



I confirm it works. (v2.3.2)
However, the performance is kind laggy.
CachyOS 6.18.19-1-cachyos-lts

<img width="1920" height="1079" alt="Image" src="https://github.com/user-attachments/assets/b1658455-ca29-484b-9b55-d0458d7ca8db" />

**Comment by IntenseWiggling** [comment]
> However, the performance is kind laggy.

When I was testing before, while performance wasn't as good as accessing fluidd directly in a browser, it was running fine; definitely accelerated.  But looking closer, it seems the webkit rendering under the device tab was being handled by my iGPU (amd processor), with the threads of the prepare/preview tabs were rendering on my dGPU (nvidia). 

If I block my igpu from being loaded so only the nvidia dgpu is available, webkit is definitely rendering via software. Resulting in huge CPU usage and laggy performance. 

So from I can tell this 'fix' is forcing orca-slicer's webkit rendering to use the mesa EGL library, and not the nvidia library. If there's some other renderer/gpu available, it it seems to run fine using that. Otherwise, it renders via software and runs like crap.

This probably isn't an ideal 'fix' for the crash issue.

**Comment by darkhog** [comment]
Might not be ideal, but it is working. It can always be replaced by something better when the root cause is found. And since the slicer's job is to generate the gcode, not drive the printer directly, so performance hit, while annoying, doesn't prevent the software from doing the job correctly.

**Comment by christiangomez24** [comment]
I updated to the last version of mainsail v2.17.0 and for me the error is gone. But I can't see the webcam. It's something.

**Comment by penkypenk** [comment]
> I updated to the last version of mainsail v2.17.0 and for me the error is gone. But I can't see the webcam. It's something.

I can confirm that after switching from fluidd to mainsail v2.17.0 it is working now! Also can see the webcam.
Everything is working fine for me now! 
Thanks a lot!

**Comment by bdavey07** [comment]
OrcaSlicer v2.3.2 installed as Flatpak on Fedora 43 with KDE Plasma 6.6.3

Printer: Elegoo Neptune 4 Pro with Klipper, Fluidd

Added variable: `WEBKIT_DISABLE_COMPOSITING_MODE=0` using Flatseal and now working.

**Comment by fronald** [comment]
Same issue.

Operating System: Fedora Linux 43
KDE Plasma Version: 6.6.3
KDE Frameworks Version: 6.24.0
Qt Version: 6.10.2
Kernel Version: 6.19.10-200.fc43.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 32 GiB of RAM (31.1 GiB usable)
Graphics Processor 1: Intel® UHD Graphics 630
Graphics Processor 2: NVIDIA GeForce GTX 1660 Ti
Manufacturer: Dell Inc.
Product Name: G5 5590

https://github.com/user-attachments/assets/6d7f51c6-bd18-4687-9b6d-f42a5c2fd148

Flatpak overrides:

```ini
[Context]
filesystems=host;host-os:ro;host-etc:ro;xdg-run/gvfsd;
sockets=session-bus;system-bus;

[Environment]
GTK_THEME=Adwaita:dark
WEBKIT_DISABLE_COMPOSITING_MODE=0
```

**Comment by arcoast** [comment]
Adding `WEBKIT_DISABLE_COMPOSITING_MODE=0` for Flatpak on Fedora KDE 44 works for me.

**Comment by nek0d3r** [comment]
Just having installed it now, I can also confirm on KDE Neon the `WEBKIT_DISABLE_COMPOSITING_MODE=0` with AppImage works for me as well.

**Comment by Dvogonen** [comment]
I am running Linux Mint 22.3 with Cinamon desktop.
I am trying to use Orcaslicer to control a Creality K1.
I have the same problem as all others above. Orcaslicer hangs when I switch to the Device tab in Orcaslicer.
The device tab just shows the fluid GUI, which works fine in a browser.
I have also tried using the latest Bambu Studio. It triggers the same problem. Bambu studio is actually worse. It hangs during startup if you have ever tried to connect to a Klipper machine previously.
Workarounds:
1) Use Flatseal to set an override variable "WEBKIT_DISABLE_COMPOSITING_MODE=0" for each application that starts the GUI. Works for both Bambu studio and Orcaslicer. Neither is able to show the webcam.
2) Switch from the default fluid interface to Mainsail. This is done by specifying both the IP adress and the Mainsail port in the Device setup. In my specific case this was 192.168.0.10:4409. The webcam does not work, but the applications do not crash.

**Comment by Tenno6** [comment]
Same issue here on bazzite. Using the port I found being used by my Q2 (10088) didn't stop it from crashing. Hopefully fixes will be included in a build soon.

**Comment by TimPasquini** [comment]
I'm on Linux Mint 22.3, kernel 6.17.0, and orca 2.3.2 flatpak

I also had the "Device" tab issue and successfully managed the workaround via the `WEBKIT_DISABLE_COMPOSTING_MODE=0` path.

**Comment by firepower9966** [comment]
This Has Been Fixed in Nightly 2.4.0-dev Build f02aa720. 

<img width="1400" height="907" alt="Image" src="https://github.com/user-attachments/assets/593e9840-9216-42c6-92ae-c28aa52ce16c" />

**Comment by Leseratte10** [comment]
Can't confirm. I'm running the exact same AppImage version on Linux (2.4.0-dev build f02aa720) and it still crashes when I access the device tab.

**Comment by firepower9966** [comment]
this is my software versions as reference.

<img width="767" height="889" alt="Image" src="https://github.com/user-attachments/assets/f2700ad3-c562-4b02-a3bb-0d9dcaa39a1f" />

**Comment by nek0d3r** [comment]
I'll test this out with my Neptune 4 Pro when I get to my shop later today and see what I experience. I just recently upgraded the firmware on it, so that shouldn't be a problem.

**Comment by thecorvidad** [comment]
It still crashes for me with the nightly Flatpack (15th of April build) on Fedora 43 using a Qidi Q2

**Comment by IntenseWiggling** [comment]
With the latest nightly's wayland change, I'm still getting the device tab crash as well.

And using the `WEBKIT_DISABLE_COMPOSITING_MODE=0` workaround either doesn't work, or causes the prepare/preview panes to now run un-accellerated.

**Comment by firepower9966** [comment]
I am using linux mint zara with cinnamon desktop and xlibre X11

**Comment by Tenno6** [comment]
> This Has Been Fixed in Nightly 2.4.0-dev Build [f02aa72](https://github.com/OrcaSlicer/OrcaSlicer/commit/f02aa7200e5373275417bf45f818d4d5bc4119a3).
> <img alt="Image" width="1400" height="907" src="https://private-user-images.githubusercontent.com/3244372/578386749-593e9840-9216-42c6-92ae-c28aa52ce16c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzYzMDQ0MTcsIm5iZiI6MTc3NjMwNDExNywicGF0aCI6Ii8zMjQ0MzcyLzU3ODM4Njc0OS01OTNlOTg0MC05MjE2LTQyYzYtOTJhZS1jMjhhYTUyY2UxNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MTZUMDE0ODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU0Nzg5ZjBiMjQ1NDZkNDEzZDM1ZmIxMDUzOGExMTk5MzJiYjBkYTNiM2M5MTBjZTRhMzc3ODVjOTljZGI4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.vKiAx41X4On1MTgGd6ZJNLMGjHkdvweEBvbAZAiSkpo">

Still crashes for me on 2.4 dev build

**Comment by domino-pl** [comment]
Tested with today's night build - not fixed :(.

**Comment by phamaralbr** [comment]
I used Flatseal to do it, and I can confim that setting `WEBKIT_DISABLE_COMPOSITING_MODE=0` as an env var fixes the issue on Orca Flatpak 2.3.2

Device tab works perfectly now.

**Comment by sgghostrider** [comment]
I got the same problem, arch/kde/wayland with Orca Slicer 2.3.2... and sadly adding "WEBKIT_DISABLE_COMPOSITING_MODE=0" doesn't work for me, it doesn't crash, yea, but it neither loads the "Device" tab anymore, it just stays blank, and it also breaks "Home" tab as well...

**Comment by russellmilliner** [comment]
Orca 2.3.2/arch (EndeavourOS)/KDE/Wayland with "WEBKIT_DISABLE_COMPOSITING_MODE=0" all tabs work for me.  I have other UI issues, but that's not this issue.

**Comment by webbwerkx** [comment]
This new 2.3.2 is completely cooked now, freezee when trying to slice any STL file....Every time they update this it fucks up now. 

Done with this fucking slicer and its bullshit.....Back to Super slicer and or Prusa

**Comment by ericderuijter** [comment]
Hi,

If you use this in the **terminal** under Ubuntu 24.04.4 LTS in the directory where your Appimage is:

" WEBKIT_DISABLE_COMPOSITING_MODE=0 ./OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.2.AppImage"

The device tab  is for me working with a Qidi Q2 printer.

If it still crashed delete first the folder:  /home/**username**/.config/OrcaSlicer/user/default/machine

Hope this helps.

**Comment by sgghostrider** [comment]
I just downloaded latest stable AppImages of 2.3.1 and 2.3.2 and also downloaded the Nightly build(Apr 28, 2026, 8:18 PM GMT+2) AppImage to test.

**Results:**

_Bare execution:_
2.3.1; Everything works stable and fast, no crashes at all and all tabs are showing and working as expected.
2.3.2; Everything besides "Devices" tab works, only crashes if printer is available and i try to access "Devices" tab.
Nighty; Exactly the same as 2.3.2

_"WEBKIT_DISABLE_COMPOSITING_MODE" set to "0":_
2.3.1: Not tested, it works fine without it.
2.3.2: Stable, doesn't crash anywhere, but "Home" and "Devices" tabs appear blank(no content is loaded).
Nighty: Unstable, UI flickers during interactions, sometimes loaded project doesn't show the objects(all plates remain empty, but still shows them on the side objects list panel), interactions are slow, constant freezes, going to the "Preview" tab may result in a crash or it bricks the UI rendering and sometimes both UI and 3D rendering, going to the "Devices" tab works almost always but interactions are choppy, and "Home" tab works as normal.

Orca runs on:
Distro: CachyOS
Kernel: 7.0.1-1-cachyos
DE: KDE Plasma 6.6.4(Wayland)
GPU: RTX 4070 (595.58.03)

Printer: QIDI Smart X3 with custom firmware
Klippain-ShakeTune: v5.1.1-0
klipper: v0.13.0-17
mainsail: v2.13.2
moonraker: v0.9.3-72

Note: Sometimes it's crashing during the "Initiallizing" part, others it shows the "Dashboard" for a second and then freezes and crashes, so whatever is making "Orca Slicer" crash is during the load of the klipper interface(and not before the load starts).

**Comment by sparkbiit** [comment]
Hi, adding my case to this thread as I've been hitting the same crash on Fedora 43 with NVIDIA.

Environment:

OS: Fedora 43
Kernel: 6.19.12-200.fc43.x86_64
DE: KDE Plasma 6.6.4 (Wayland)
GPU: NVIDIA (driver 580.142)
OrcaSlicer: v2.3.2 AppImage + Flatpak (same crash on both)

Issue:
Device tab crashes with SIGSEGV on both AppImage and Flatpak builds. Crash occurs immediately when clicking the Device tab with a Klipper/Mainsail printer configured.
Tested workarounds (none worked):

WEBKIT_DISABLE_DMABUF_RENDERER=1 — no effect
WEBKIT_DISABLE_COMPOSITING_MODE=1 — no effect
WEBKIT_DISABLE_COMPOSITING_MODE=0 — no crash but Device and Home tabs load blank
GDK_BACKEND=x11 — same crash
DRI_PRIME=0 — same crash
Flatpak runtime update (org.freedesktop.Platform.GL.nvidia-580-142) — same crash

Crash location (consistent across all attempts):
#0 WebKit::AcceleratedBackingStore::update(WebKit::LayerTreeContext const&) (libwebkit2gtk-4.1.so.0 + 0x9106b2)
#1 WebKit::DrawingAreaProxyCoordinatedGraphics::enterAcceleratedCompositingMode
Note: DRI_PRIME warning also present on every launch:
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
This system has only one GPU (NVIDIA discrete), so DRI_PRIME=1 set by OrcaSlicer is invalid.

Hope this helps narrow down the issue. Happy to provide additional debug info if needed.

**Comment by eriksl** [comment]
Same here with flatpak on Fedora. Doesn't matter what environment I set, it keeps crashing.

I see this issue has been reported initially in september 2025, so I guess a fix isn't to be expected quite soon. So I guess I'll stick to CrealityPrint for the time being. Which is ugly in various aspects, but at least just works.

**Comment by sgghostrider** [comment]
> Same here with flatpak on Fedora. Doesn't matter what environment I set, it keeps crashing.
> 
> I see this issue has been reported initially in september 2025, so I guess a fix isn't to be expected quite soon. So I guess I'll stick to CrealityPrint for the time being. Which is ugly in various aspects, but at least just works.

If you are willing to downgrade that much just use the previous version of Orca(2.31) through it's AppImage... and don't be scared by the "Ubuntu" in the name, AppImages are universal same as flatpaks, just download it to your desktop and run it from there for the time being... 😉

**Comment by IntenseWiggling** [comment]
Anyone else update to the [latest fluidd ](https://github.com/fluidd-core/fluidd/tree/v1.37.0)from a few days, and notice the device tab in orca not crashing? It runs really bad though; jerky, high cpu and memory.

**Comment by eriksl** [comment]
> > Same here with flatpak on Fedora. Doesn't matter what environment I set, it keeps crashing.
> > I see this issue has been reported initially in september 2025, so I guess a fix isn't to be expected quite soon. So I guess I'll stick to CrealityPrint for the time being. Which is ugly in various aspects, but at least just works.
> 
> If you are willing to downgrade that much just use the previous version of Orca(2.31) through it's AppImage... and don't be scared by the "Ubuntu" in the name, AppImages are universal same as flatpaks, just download it to your desktop and run it from there for the time being... 😉

I downgraded the flatpak to the previous version and it has exactly the same problem. So I didn't bother trying the appimage (which I'd rather avoid anyway). Isn't there someone that creates RPM packages? It looks like the source is open, so I guess it should be possible?

**Comment by Riztard** [comment]
Running aur/orca-slicer-bin 2.3.2-3 on EndeavourOS/KDE/Wayland with "WEBKIT_DISABLE_COMPOSITING_MODE=0" works for me 👍

**Comment by eriksl** [comment]
Unfortunately not for me, I tried all (4) environment workarounds, using flatpak on Fedora.

**Comment by arcoast** [comment]
> Unfortunately not for me, I tried all (4) environment workarounds, using flatpak on Fedora.

It is strange, it definitely seems to work for some people and not others, I'm one of the lucky ones I guess, and it's worked for me using Flatpak on Fedora KDE on both v43 and v44.

**Comment by eriksl** [comment]
I am still on Fedora 42, maybe that's the issue. I am planning to upgrade soon.

**Comment by SoftFever** [comment]
Hey guys, unfortunately, there's not much we can do in OrcaSlicer since webkit2gtk crashes at the OS system level.

can you try to upgrade the Fluidd or report the issue there see if the dev can apply the fix?
For reference, mainsail has this fix:
https://github.com/mainsail-crew/mainsail/issues/2346

**Comment by lusanagi** [comment]
> Hey guys, unfortunately, there's not much we can do in OrcaSlicer since webkit2gtk crashes at the OS system level.
> 
> can you try to upgrade the Fluidd or report the issue there see if the dev can apply the fix? For reference, mainsail has this fix: [mainsail-crew/mainsail#2346](https://github.com/mainsail-crew/mainsail/issues/2346)

I was on an older version of mainsail and had the issue (even if they say in the mainsail one that AMD + Webkitgtk might work, it didn't), but after updating it to 2.17 I can confirm it is working

**Comment by jmelen** [comment]
Finally working with fluidd 2.17 but performance is terrible on the Device tab.

**Comment by Riztard** [comment]
> Finally working with fluidd 2.17 but performance is terrible on the Device tab.

you mean mainsail 2.17

**Comment by jmelen** [comment]
> > Finally working with fluidd 2.17 but performance is terrible on the Device tab.
> 
> you mean mainsail 2.17

Sorry, we're both wrong. I meant fluidd 1.37. I don't use mainsail.

**Comment by Boyfinn** [comment]
I get the same issue with my klipper/mainsail printer. I see the loading screen and then briefly the mainsail frontpage for my printer after which OrcaSlicer freezes and then crashes silently with a segfault.

os: Debian 13 (trixie) x86_64
kernel: 6.12.88+deb13-amd64
de: plasma 6.3.6

**Comment by lusanagi** [comment]
> I get the same issue with my klipper/mainsail printer. I see the loading screen and then briefly the mainsail frontpage for my printer after which OrcaSlicer freezes and then crashes silently with a segfault.
> 
> os: Debian 13 (trixie) x86_64 kernel: 6.12.88+deb13-amd64 de: plasma 6.3.6

Updating to the latest version (2.17) fixes it

**Comment by givver** [comment]
I added the following to my Environment variables in the OrcaSlicer .desktop file (or use the menu editor) and it fixed it completely for me.
WEBKIT_DISABLE_COMPOSITING_MODE=0 WEBKIT_DISABLE_DMABUF_RENDERER=0

**Comment by Oneseat1** [comment]
> I added the following to my Environment variables in the OrcaSlicer .desktop file (or use the menu editor) and it fixed it completely for me. WEBKIT_DISABLE_COMPOSITING_MODE=0 WEBKIT_DISABLE_DMABUF_RENDERER=0

this didn't work for me did you just add this to a new line or anything else before it? could you share a screen shot of your .desktop file?

**Comment by RobJM99** [comment]
The exact problem started today after aborting a print.
Linux Mint 22.3 kernel 6.14.0-37-generic
OrcaSlicer 2.3.2 build c724a3f FlatPak from FlatHub

**Comment by RobJM99** [comment]
i tried adding the env vars to the desktop file, but as I am running from flatpak, it continues with the same issue.  orcaslicer flatpak is forcing the webkit to be used but the webkit is incompatible with the recent kernel update (according to various ai searches).  
temporary workaround: open fluidd in chrome and DO NOT TOUCH THE DEVICE TAB - shouting at myself to not forget

is there any way to disable the DEVICE tab so that it is not accidently touched? ..until OrcaSlicer is fixed...

**Comment by givver** [comment]
I am using the flatpak version too. This is the full contents of my com.orcaslicer.OrcaSlicer.desktop

[Desktop Entry]
Categories=Graphics;3DGraphics;Engineering;
Comment=
Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=0 WEBKIT_DISABLE_DMABUF_RENDERER=0 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=entrypoint --file-forwarding com.orcaslicer.OrcaSlicer @@u %U @@
GenericName=3D Printing Software
Icon=com.orcaslicer.OrcaSlicer
Keywords=3D;Printing;Slicer;slice;3D;printer;convert;gcode;stl;obj;amf;SLA
MimeType=model/stl;model/3mf;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;application/x-amf;x-scheme-handler/orcaslicer;
Name=OrcaSlicer
NoDisplay=false
Path=
PrefersNonDefaultGPU=false
StartupNotify=false
StartupWMClass=orca-slicer
Terminal=false
TerminalOptions=
Type=Application
X-Desktop-File-Install-Version=0.28
X-Flatpak=com.orcaslicer.OrcaSlicer
X-KDE-SubstituteUID=false
X-KDE-Username=

**Comment by miguelbaldi** [comment]
The easiest workaround, just run one time:
`flatpak --user override --env=WEBKIT_DISABLE_COMPOSITING_MODE=0 --env=WEBKIT_DISABLE_DMABUF_RENDERER=0 com.orcaslicer.OrcaSlicer`
After that, just open Orca Slicer and be happy. Does not require editing desktop entries.

**Comment by RobJM99** [comment]
@miguelbaldi  I tried your fix, the device tab opens as a blank white page, no Fluidd.  but at least orcaslicer does not crash.

**Comment by matikij** [comment]
@miguelbaldi I can confirm that your fix worked for me flawlessly - no crash, device page opens correctly.

**Comment by Greg6087** [comment]
@miguelbaldi I can also confirm that your fix worked for me flawlessly - no crash.  Nice work!

**Comment by Oneseat1** [comment]
> I am using the flatpak version too. This is the full contents of my com.orcaslicer.OrcaSlicer.desktop
> 
> [Desktop Entry] Categories=Graphics;3DGraphics;Engineering; Comment= Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=0 WEBKIT_DISABLE_DMABUF_RENDERER=0 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=entrypoint --file-forwarding com.orcaslicer.OrcaSlicer @[@U](https://github.com/U) %U @@ GenericName=3D Printing Software Icon=com.orcaslicer.OrcaSlicer Keywords=3D;Printing;Slicer;slice;3D;printer;convert;gcode;stl;obj;amf;SLA MimeType=model/stl;model/3mf;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;application/x-amf;x-scheme-handler/orcaslicer; Name=OrcaSlicer NoDisplay=false Path= PrefersNonDefaultGPU=false StartupNotify=false StartupWMClass=orca-slicer Terminal=false TerminalOptions= Type=Application X-Desktop-File-Install-Version=0.28 X-Flatpak=com.orcaslicer.OrcaSlicer X-KDE-SubstituteUID=false X-KDE-Username=

This worked for me after a reboot. I'm not running the flatpak version.

**Comment by dreanmer** [comment]
@miguelbaldi I just wanna thank you for this solution. It had been affecting me for months!

**Comment by thelazurus** [comment]
@miguelbaldi worked for me with v2.3.2 on Linux with a Qidi Q2. Thanks again!

**Comment by SoftFever** [comment]
We’re in a limbo situation with Linux. We set `WEBKIT_DISABLE_COMPOSITING_MODE=1` because it resolves crashes for many users depending on their Linux distro and hardware combination — but it has the opposite effect for another group of users with different distro and hardware setups.

**Comment by darkhog** [comment]
> We’re in a limbo situation with Linux. We set `WEBKIT_DISABLE_COMPOSITING_MODE=1` because it resolves crashes for many users depending on their Linux distro and hardware combination — but it has the opposite effect for another group of users with different distro and hardware setups.

Since it's just one variable, couldn't an automated system be set up that would create binaries for both =0 and =1 variants so people one doesn't work for can try the other?

**Comment by burkfers** [comment]
This should be fixed by #13724, and as of #14039, if you're on Wayland and the original fix results in a laggy printer tab, forcing x11 mode with `GDK_BACKEND=x11` should make it snappy again.
Thank you, SoftFever and igiannakas!

**Comment by Greg6087** [comment]
Excellent!  Great work and an amazing product.

**Comment by sgghostrider** [comment]
> This should be fixed by [#13724](https://github.com/OrcaSlicer/OrcaSlicer/pull/13724), and as of [#14039](https://github.com/OrcaSlicer/OrcaSlicer/pull/14039), if you're on Wayland and the original fix results in a laggy printer tab, forcing x11 mode with `GDK_BACKEND=x11` should make it snappy again. Thank you, SoftFever and igiannakas!

Arch KDE+Wayland, tried the latest AppImage nightly build from today(41ff0f9) and yes, it doesn't crash anymore and all tabs appear normal, only drawback is that the klipper page is really choppy, NOT unresponsive, just "choppy", like when you disable hardware acceleration for the browser, which i can live with.

Adding "`GDK_BACKEND=x11`" makes "Home" and "Devices" tab appear blank/gray as previous user suggested "workarounds" did, but it seems it's some kind of a rendering issue, because if i blind click where my recent projects should be i can open them(can't verify for Devices tab as there isn't any clear feedback to my actions).

**Comment by igiannakas** [comment]
Hm interesting. Can you please confirm your webkitgtk version?

**Comment by sgghostrider** [comment]
> Hm interesting. Can you please confirm your webkitgtk version?

I don't know if you meant me, but this is what i got "webkit2gtk-4.1 2.52.4-1", still i don't know why would that be relevant as AppImages do not pull packages from my system as they are "self-contained"(which is exactly the reason i'm testing on them), so whatever the dev made the AppImage with is what it's using...

**Comment by Vasenq** [comment]
I can confirm that this was an issue on my debian system, but since ive build myself the 2.5.0-dev version i haven't experienced no crashes when switching to device tab
