### ISSUE TITLE
Orca Slicer - Newer 3mf version

### ISSUE THREAD

**Issue by ETS5** [SoftFever/OrcaSlicer#1349]
**Describe the bug**
The 3mf's version 1.6.2.4 is newer than Orca Slicer's version 1.6.0.66, Found following keys unrecognized:
-extruder_clearance_max_radius;
You should update your software

**3mf File for This Bug**
any 3mf I saved from bambu studio

**To Reproduce**
save a 3mf from bambu and open it in Orca

**Expected behavior**
for the Slicer to be updated

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/35798060/512a0217-9a7d-4b4a-ac12-619224c448b5)

**Printer model**
Bambu Labs X1C

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Comment by neelyrock** [comment]
Can confirm I am also seeing this on Mac OS (Ventura 13.4).

**Comment by fourtwizzy** [comment]
@SoftFever Low hanging fruit. This was resolved in the nightly builds complements of commit [bdf8c8d](https://github.com/SoftFever/OrcaSlicer/commit/bdf8c8d5b1b1ef87c392f54124371cdfed79650f).
Obviously it hasn't been pushed to the latest release, but easy to track and close :)

**Comment by xCROv** [comment]
This is still occurring. I encountered it with [this](https://makerworld.com/en/models/2082080-arc-raiders-stitcher-light-submachine-gun-prop?from=search#profileId-2249997) 3mf. 

<img width="717" height="212" alt="Image" src="https://github.com/user-attachments/assets/3f75a8d7-7f0c-4e71-911b-94edee05cc9a" />

**Comment by LJKraus** [comment]
Much has changed since 2023.

Version numbers of Bambu Studio and OrcaSlicer are normally different.  

And, your example shows no unrecognized values.

**Comment by artisancreek** [comment]
While that may be true @LJKraus , I too am getting the exact same (versions too) message box and having just downloaded Orca Slicer (v2.3.1) it seems this difference in versions should be ignored based on your comment? Is this "check" needed in the software?

<img width="792" height="183" alt="Image" src="https://github.com/user-attachments/assets/1fff2bfb-9bd8-44fe-afe3-99e3ad083e00" />

<img width="810" height="220" alt="Image" src="https://github.com/user-attachments/assets/e688b5c6-a0b9-41f0-bd0c-4b497bc887ea" />

Model downloaded from MakerWorld (https://makerworld.com/en/models/2032566-pi-cookie-cutter#profileId-2192125)

MacBook Pro 2021, M1 Max, 32 GB, Tahoe 26.2
