### ISSUE TITLE
[1.6.4] Not connecting to server

### ISSUE THREAD

**Issue by Ohmarinus** [SoftFever/OrcaSlicer#1877]
**Update**
This issue can be temporarily solved by logging out, and then logging back in.
Thanks to a user on the Orca Discord (AXnightroad/auafuma) who mentioned this fixed their issue. Sadly, the issue returns once the app is restarted!

**Describe the bug**
The Beta version and Bambu Studio are both connecting to my machine fine but the latest version of Orca doesn't want to 'connect to server'. I tried both the portable and the installer version for Windows but no connection can be made. I chose to allow the software to connect to private networks, just like I always do.

I am using the latest version of Bambu Studio and have installed the network plugins correctly and it's all working normally.

**To Reproduce**
Start the software, go to the Device pane and there it is:
![image](https://github.com/SoftFever/OrcaSlicer/assets/5002107/ca7f6c25-0f47-4f6c-89aa-d21004b83a4d)

It sees the machine, but it can't connect to the server. Despite the beta version and BS being able to connect perfectly fine.

**Expected behavior**
To be able to send a print

**Screenshots**
![image](https://github.com/SoftFever/OrcaSlicer/assets/5002107/5beb22bd-be40-4ae3-aaff-4de07866c50a)

**Printer model**
Bambu Lab X1C

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Edit:**
A user on discord mentioned to me that for them it wouldn't connect, but the camera feed worked. So I tried, and well, camera feed works fine, yet you can't print with it:
![image](https://github.com/SoftFever/OrcaSlicer/assets/5002107/5b562900-ee25-4da1-86a1-98730bf42bfc)

**They also mentioned that logging out and back in to their Bambu account would fix this issue!**

**Comment by FlyingLemming** [comment]
Same here, running on macOS 13.5

**Comment by STC148** [comment]
I have the same problem, win11

**Comment by auafuma** [comment]
I had same issue, logged out of my bambu account and back in again, then I was able to connect fine.

**Comment by Ohmarinus** [comment]
> Sorry, does not seem to be solved at all. Logging out and in again works fine for the moment. However, after restarting OrcaSlicer, the issue is there again. I need to repeat the procedure each and every time I launch the app.
> 
> macOS 13.5, Apple Silicon

Thanks for letting me know, I just found this out myself as well, I reopened the issue and updates the description.

**Comment by CoryCharlton** [comment]
Same issue here :(

**Comment by shyblower** [comment]
Logging in and out does not work for me on Linux. Maybe because Orca crashes on logout.

**Comment by FlyingLemming** [comment]
On macOS, I initially thought that OrcaSlicer has crashed upon logout. However, it just took one or two minutes, then it succeeded. All further logout attempts took only a second.

**Comment by capsel22** [comment]
can confirm, logging out of Orca, closing down, opening, logging  back in worked.

**Comment by FlyingLemming** [comment]
Then close Orca once more and restart – it will most probably not work anymore.

**Comment by Ohmarinus** [comment]
> can confirm, logging out of Orca, closing down, opening, logging back in worked.

As stated, the settings disappear after closing and reopening Orca again after fixing it. It doesn't seem to get stored correctly.

**Comment by capsel22** [comment]
Yes correct, issue returns after re-opening Orca.

**Comment by psiberfunk** [comment]
Same problem here @SoftFever .  Seems that this has been reproduced by lots of people at this point.

**Comment by Macmagoo** [comment]
Same problem here. Camera feed works but no server connection.

**Comment by psiberfunk** [comment]
possible candidates commits:

- https://github.com/SoftFever/OrcaSlicer/commit/6e1bdaf9d43f0aa6be7e881d03e9b3154748735e
- https://github.com/SoftFever/OrcaSlicer/commit/9e73dfeb5d32ad3b1020137f3ee74d826c3a9470

**Comment by psiberfunk** [comment]
last valid working windows nightly build appears to be https://github.com/SoftFever/OrcaSlicer/actions/runs/5915113014 folks

**Comment by msteele999** [comment]
same issue here - Windows 11 Home.

Only seems to affect my X1CC and not my Voron

**Comment by SoftFever** [comment]
Thanks guys.
I'm aware of this issue, will investigate and release hotfix soon

**Comment by SoftFever** [comment]
> last valid working windows nightly build appears to be https://github.com/SoftFever/OrcaSlicer/actions/runs/5915113014 folks. All main branch builds (on github.. i don't have a windows build environment) after this one fail for this bug. I suspect this commit is the problem @SoftFever : [6e1bdaf](https://github.com/SoftFever/OrcaSlicer/commit/6e1bdaf9d43f0aa6be7e881d03e9b3154748735e)

Thanks.
I have pinpointed the issue, but I can only work on it tonight after work. Should be able to release a hotfix today or tomorrow

**Comment by FlyingLemming** [comment]
No hurries. 🤗
Thank you for your efforts and this magnificent piece of software!

**Comment by swdw973** [comment]
Glad they reopened this. Using a work around does not constitute solving the problem.  

Even more glad they found the issue so they can fix it. Great job!!!

**Comment by SoftFever** [comment]
Hey guys,

Can someone help me verifying if this issue is fix with this build(it should be ready in 25 minutes)?
https://github.com/SoftFever/OrcaSlicer/actions/runs/5952301579

**Comment by Naninani** [comment]
@SoftFever the fix is working for me on Apple silicon.

**Comment by Ohmarinus** [comment]
> Hey guys,
> 
> Can someone help me verifying if this issue is fix with this build(it should be ready in 25 minutes)? https://github.com/SoftFever/OrcaSlicer/actions/runs/5952301579

Connections seems to be made for me! Uploading and printing something now :)

No need to relog within Orca anymore, so for me, I can confirm at least the Win10 portable version works.

**Comment by FlyingLemming** [comment]
Same here. Started the macOS/ARM app and the printer has been detected right away.

**Comment by SoftFever** [comment]
I will bump the version then.
Will publish a new hotfix tomorrow.

**Comment by msteele999** [comment]
I can test Windows version in 30 minutes

sent from my mobile device.

**Comment by capsel22** [comment]
> I will bump the version then. Will publish a new hotfix tomorrow.

thanks for the quick fix!

**Comment by SurgeHawk** [comment]
Windows seem to be working now

**Comment by msteele999** [comment]
Confirmed working for me as well

**Comment by Ohmarinus** [comment]
Since this issue is resolved, I will update the issue and close this issue. Thanks for the quick fix @SoftFever

**Comment by RedstoneGuy9248** [comment]
the issue still happens when stealth mode is enabled
the error that logs when it happens:
`[error]	2026-06-04 18:58:24.311680[Thread 0x00007a74d7dd54c0]:publish_json: {"pushing":{"command":"pushall","push_target":1,"sequence_id":"20028","version":1}} code: -2`
disabling stealth mode fixes it

**Comment by RedstoneGuy9248** [comment]
from commit 2aefba2:
```cpp
            if (is_user_login() && app_config->get("stealth_mode") == "false") {
              // this->check_privacy_version(0);
              request_user_handle(0);
            }
```
i believe these are the lines that are causing the issue
