### ISSUE TITLE
Pressure Advance - Line : Plate boundaries error

### ISSUE THREAD

**Issue by dJOS1475** [SoftFever/OrcaSlicer#2581]
### OrcaSlicer Version

1.8.0

### OS version

macOS 14.1

### Additional system information

"2018" Intel Mac Mini

### Printer

Custom w/ 225x225mm bed and -10mm X & Y origin

### How to reproduce

Create PA advance Line test eg 0.02 - 0.08 with 0.002 increments
Slice model 

### Actual results

Error: A G-code path goes beyond plate boundaries

### Expected results

No error. 
The sliced model is clearly within bounds

![Screenshot 2023-11-02 at 2 43 16 pm](https://github.com/SoftFever/OrcaSlicer/assets/39177227/4c3ca78c-5e34-4225-91e8-b1f5c2c0f8c6)
![SCR-20231102-navr](https://github.com/SoftFever/OrcaSlicer/assets/39177227/c8dde357-917c-4b33-982f-1998c828b01a)

### Project file & Debug log uploads

[debug_Thu_Nov_02_13_35_13_35539.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/13234060/debug_Thu_Nov_02_13_35_13_35539.log.0.zip)

[Pressure Advance Test.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13234072/Pressure.Advance.Test.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by A-Printer** [comment]
I have a similar problem with PA calibration, while generating PA Line with default options. In my case, the lines are generated partly out of the build plate.

**OrcaSlicer Version**

1.8.0-beta2

**OS version**

Same issue on macOS and Windows

**Printer**

FlashForge Adventurer 5M

**How to reproduce**

Create PA advance Line with default settings
Slice model

**Actual results**

The "PA Test" texts appears centered on the build plate. But when I slice it, the lines appear partially out of the plate (see screenshot).

<img width="699" alt="Capture d’écran 2023-11-10 à 16 55 17" src="https://github.com/SoftFever/OrcaSlicer/assets/87852864/9b585672-1931-4582-9188-0f6116a64ce7">

If I move the "PA Test" text on the plate and slice I get this very unhelpful error message:

<img width="443" alt="Capture d’écran 2023-11-10 à 16 56 24" src="https://github.com/SoftFever/OrcaSlicer/assets/87852864/edbad6f6-7350-491f-8958-0c938286c42f">

**Comment by A-Printer** [comment]
If I set the origin to 0, 0 instead of the default 110, 110 (which makes the arrows appear at the center of the plate instead of the lower left) the preview is now shown correctly inside the build plate boundaries, but when I give the gcode file to the printer it detects that it's going to print outside of boundaries. I observed the same issue with the Max flowrate calibration.

**Comment by H8ted666** [comment]
It's still doing it. For whatever reason it sets the center to 0x0 regardless of settings.

**Comment by PeonyThePeon** [comment]
I encountered this in version 2.3.2, build c724a3f5 on Ubuntu 24.04.4 LTS.

Update: I found a newer bug report (#11965) for the same issue, which reports that it has been fixed in development and presumably should be fixed in future releases.

**Comment by wmahmoud** [comment]
This is still happening as of today in 2.3.2.

OrcaSlicer Version

2.3.2.

OS version

Windows 10

Printer

Elegoo Centauri Carbon

How to reproduce

Create PA advance Line with default settings
Slice model
