### ISSUE TITLE
Checking for updates doesn't work on Mac and Windows

### ISSUE THREAD

**Issue by szafranski** [SoftFever/OrcaSlicer#2622]
### OrcaSlicer Version

since circa 1.7

### OS version

Mac Sonoma and Windows 11

### Printer

Prusa i3 and Creality 10S

### How to reproduce

Open an app or check for updates manually

### Actual results

No prompt regarding possible update 

### Expected results

Prompt or info when update is available. It worked few weeks ago but it is not since some time. On both systems

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13259836/log.zip)
[debug.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13259847/debug.3mf.zip)

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by SoftFever** [comment]
Thank you for reporting this.
Fixed in dev branch

**Comment by seanbrockest** [comment]
Can we reopen this? Hasn't worked in the last few versions. I just did a clean install on a clean install of windows 10, and it's still broken. Currently using 2.0.0

**Comment by prsk8er735** [comment]
> Thank you for reporting this. Fixed in dev branch

Agree with the user above this needs to be reopened. Windows installation v2.1.1 and check for updates does nothing. No prompt no pop update nothing.

**Comment by FelixBuehler** [comment]
Can confirm.
I do recall, that i once got a notification for a beta update. Denied that and since then it's broken.
