### ISSUE TITLE
Fuzzy skin when blocked with modifier shows up as fuzzy line in model where edge of modifier is

### ISSUE THREAD

**Issue by HappyOldtimer** [SoftFever/OrcaSlicer#2647]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Printer

Prusa MK3S+

### How to reproduce

Load model
Apply fuzzy skin
Load modifier
Set fuzzy skin off for modifier
See lines in sliced model
![image](https://github.com/SoftFever/OrcaSlicer/assets/100432441/1a517a38-acc7-4649-a4f5-619dd0cb6396)
![image](https://github.com/SoftFever/OrcaSlicer/assets/100432441/3fa3df1a-7f06-4bca-88a4-cd893212a9ea)

### Actual results

Top surface marred by fuzzy edges of modifiers that should not print at all.

### Expected results

No visual marring of the model to print.

### Project file & Debug log uploads

[BHZ top RB test OrcaSlicer 170.zip](https://github.com/SoftFever/OrcaSlicer/files/13282625/BHZ.top.RB.test.OrcaSlicer.170.zip)

##
[debug_Mon_Nov_06_17_36_11_11088.log.zip](https://github.com/SoftFever/OrcaSlicer/files/13294511/debug_Mon_Nov_06_17_36_11_11088.log.zip)
# Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by DVSVIDEO** [comment]
This is an old problem. It generates extra walls at the boundary of the modifier.
It was already in the Prusaslicer. I reported it but it is not solved until today.

one of many reports, for example: https://github.com/prusa3d/PrusaSlicer/issues/7847

**Comment by HappyOldtimer** [comment]
Right. Well, that might make it more interesting then, since it doesn't
happen in PrusaSlicer 2.6.x. (am not @ the office, do not know the last
digit off the top of my head)

So this has been solved in PrusaSlicer,  apparently : -)

Paul

**Comment by DVSVIDEO** [comment]
_"So this has been solved in PrusaSlicer,  apparently : -)"_
**Are you sure?  The newest Prusaslicer available today:**
![Fuzzy problem](https://github.com/SoftFever/OrcaSlicer/assets/96373457/fa4b8694-d8bd-42d8-8734-26602af32dcc)

**Comment by DVSVIDEO** [comment]
That's why I asked, https://github.com/prusa3d/PrusaSlicer/issues/9787  and several of us have asked  https://github.com/prusa3d/PrusaSlicer/issues/9787 , for a painting tool, so that the fuzzy skin can be created where you paint it.
It only makes sense on the outer surface anyway. Currently a modifier body penetrates the model and creates the fuzzy skin where it is not needed.
https://github.com/prusa3d/PrusaSlicer/issues/9353
https://github.com/prusa3d/PrusaSlicer/issues/11594
Whoever solves this first will get the glory...

**Comment by HappyOldtimer** [comment]
Sorry for late reaction, have been away couple of days.
But actually: this is in Prusaslicer, with cylinder and no edge lines... so from my perspective it seems solved in Prusaslicer...??
![image](https://github.com/SoftFever/OrcaSlicer/assets/100432441/4a003a78-2329-4dab-aecb-4812d29c3f66)
![image](https://github.com/SoftFever/OrcaSlicer/assets/100432441/b16c952d-4e3d-4feb-94c0-35f674822ea1)

Cheers,
Paul

**Comment by DVSVIDEO** [comment]
> Sorry for late reaction, have been away couple of days. But actually: this is in Prusaslicer, with cylinder and no edge lines... so from my perspective it seems solved in Prusaslicer...?? ![image](https://user-images.githubusercontent.com/100432441/283396167-4a003a78-2329-4dab-aecb-4812d29c3f66.png) ![image](https://user-images.githubusercontent.com/100432441/283396362-b16c952d-4e3d-4feb-94c0-35f674822ea1.png)
> 
> Cheers, Paul

No Paul, it's not solved, you're just doing something else.
Look at my photo, the latest Prusaslicer hasn't fixed this bug either.
If you insert a modifier body into your model and turn on the "Fuzzy skin" of the modifier, it creates walls inside.

**Comment by HappyOldtimer** [comment]
Interesting, because that is exactly what i did, although i did not mention it explicitly because this is what my issue is about. 
So to be clear: I have added a cylinder modifier,  added the property 'fuzzy skin' to it with the checkbox uncheked, just like i did in my initial post. 
My post is about the fact that with a modifier with the fuzzy skin property added but turned off, it still produces those wall lines in Orca, but not in the PrusaSlicer version i am using. 
Im fine with it if i am indeed doing something else, but i dont think i am...

**Comment by DVSVIDEO** [comment]
Okay. I followed the list mentioned in the first post:
Load model
Apply fuzzy skin
Load modifier
Set fuzzy skin off for modifier
See lines in sliced model

Here are the results:
![Fuzzy issue](https://github.com/SoftFever/OrcaSlicer/assets/96373457/f9ac1c68-d46f-4df4-9a74-e57bf3990c43)

**Comment by HappyOldtimer** [comment]
To doublecheck, I did the same as what you did:
Load model
Apply fuzzy skin
Load modifier
Set fuzzy skin off for modifier
See lines in the sliced model.

And I got the same results you dit.
However:
When I look at the model I started this thread with, the behaviour is different. I have loaded a model, applied fuzzy skin, added two modifiers with fuzzy skin off, and there I have no lines in the sliced model...
And that is what I do not understand.

![image](https://github.com/SoftFever/OrcaSlicer/assets/100432441/c67532ce-214b-4315-ab42-87439c1f63c4)
![image](https://github.com/SoftFever/OrcaSlicer/assets/100432441/b8b13aba-e37d-4760-acc6-c8c984088c5a)
