### ISSUE TITLE
Doesn't slice anymore. A fatal error occurred: "Access violation"

### ISSUE THREAD

**Issue by FillPavS** [SoftFever/OrcaSlicer#3158]
### OrcaSlicer Version

from Actions (Full re-write of spiral vase (#3091))

### OS version

Windows 10

### Printer

Bambu Lab X1C

### How to reproduce

Open the slicer, add any primitive or model, slice it.

### Actual results

A fatal error occurred: "Access violation". There are no errors on the earlier version dated 09 Dec 23 (Port Emboss & SVG gizmo from PrusaSlicer (#2819))

![Снимок экрана (145)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/ccc9cc5e-4ff8-4ab5-9c63-a9de94058ca6)

### Expected results

Obviously there should be no error.

### Project file & Debug log uploads

[debug_Sun_Dec_17_11_07_18_1396.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/13695191/debug_Sun_Dec_17_11_07_18_1396.log.0.zip)
[Cute Baby Dragon Fauna.zip](https://github.com/SoftFever/OrcaSlicer/files/13695192/Cute.Baby.Dragon.Fauna.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SoftFever** [comment]
Thank you.
Fixed in this build: https://github.com/SoftFever/OrcaSlicer/actions/runs/7238476339

**Comment by tlhintoq** [comment]
So if this was fixed in the build of 23-12-17...
Shouldn't it be part of 23-12-21?  Because I'm getting the same fatal exception in 23-12-21
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/8709b327-3135-4fc3-9b91-03c981be9cfd)

**Comment by tlhintoq** [comment]
@SoftFever @Noisyfox 
I'm still getting this `Access Violation` bug with newer builds.
For example:  Nightly build 2312122 is several days newer. Shouldn't this fix be included to newer builds?
https://github.com/SoftFever/OrcaSlicer/actions/runs/7294849330
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/388c2aa6-6cce-4a5a-b40a-d1560623d040)

**Comment by tlhintoq** [comment]
@Noisyfox @SoftFever 
Might be worth noting that the nightly build linked above has the error yet this PR release slices fine.
https://github.com/SoftFever/OrcaSlicer/actions/runs/7300472441

**Comment by SoftFever** [comment]
> @Noisyfox @SoftFever Might be worth noting that the nightly build linked above has the error yet this PR release slices fine. https://github.com/SoftFever/OrcaSlicer/actions/runs/7300472441

Thank you.
Can you shared your project file?

**Comment by tlhintoq** [comment]
[Square_Nathans.zip](https://github.com/SoftFever/OrcaSlicer/files/13757896/Square_Nathans.zip)
@SoftFever There ya go.  But it was happening with anything I dropped on a fresh build plate.

**Comment by RoyMarok** [comment]
Hi. Got this bug on 2.0.0. Perfect working since 12.05.2024. Start crushing on slicing step 16.06.2024. In 1-st half of day of 17.06.2024 work as normal. I think this issue local time depended. 
AMD Ryzen 7 7700X, RAM 64, Win10, AMD Radeon 6650XT, Creality Ender 3v3KE
