### ISSUE TITLE
Custom Filaments missing from AMS list

### ISSUE THREAD

**Issue by clively** [SoftFever/OrcaSlicer#4431]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambu Lab P1S w/AMS

### How to reproduce

1. Go to the Device page
2. Look at the AMS section on the right hand side.  Notice that one or more of the filaments will not show as loaded.  Prior versions of the software show all of them loaded.
3. Double click on a slot to set the filament.

### Actual results

Notice that the custom filaments are NOT shown.

### Expected results

I expect to see all of my custom filaments to be listed along with the standard ones.  

### Project file & Debug log uploads

This is not project specific.   The info shown on the Device Information page is wrong and the behavior of the filament selection is wrong.   See other notes.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

Screen shots of what is WRONG:

![MissingFromAMS](https://github.com/SoftFever/OrcaSlicer/assets/392564/9befa88c-acda-46d1-9b80-8b0395c53a1d)
![MissingFromList](https://github.com/SoftFever/OrcaSlicer/assets/392564/578d58b5-7075-4906-b866-4ace01522af3)

Screen shots of what it looks like under version 1.9 (which is correct):

![GoodFromAMS](https://github.com/SoftFever/OrcaSlicer/assets/392564/8e70285b-94c9-40c6-a5b1-9c16ae39d5a0)
![GoodFromList](https://github.com/SoftFever/OrcaSlicer/assets/392564/85358498-60af-4d29-bbfc-5b20a748e7ef)

**Comment by bcpux** [comment]
Same issue here after updating to the beta on a BambuLab A1 with AMS Lite.

**Comment by Unit210** [comment]
I second this issue, custom filament had trouble importing and some seem to have been corrupted, they have the right name but no presets and cannot be deleted. No custom filament shows on AMS selection.

**Comment by plexi32** [comment]
i can choose my own Generic PLA(orange, K=0,04), it still shows some Support PLA, but colour and K-factor are shown correctly, so it is only the wrong name displayed.
![filament wrong](https://github.com/SoftFever/OrcaSlicer/assets/58932224/697a1e66-5c27-423f-b2bd-0922488ee8ce)

**Comment by SkasLT** [comment]
Same issue here with OrcaSlicer V2.0.0 Beta Release, i use Bambu lab P1S

**Comment by nashchelsy** [comment]
Same here, I downgraded back to v1.9.1 for now.

**Comment by Unit210** [comment]
> I second this issue, custom filament had trouble importing and some seem to have been corrupted, they have the right name but no presets and cannot be deleted. No custom filament shows on AMS selection.

EDIT i was looking at the JSON of my profiles and notices the "filament_id" is set to "null" on my missing ones. If somebody knows how these are generated i would like to try manually putting one to see if it will recognize it. here's an example "P8a845c8"

**Comment by Daredevll** [comment]
Same here, no custom filaments are present in the AMS filament selection dropdown. Tried both install and portable version - no difference. In 1.9.0 they show as expected

**Comment by storm77de** [comment]
Still an issue after upgrading to 2.0.0

**Comment by Gozania** [comment]
Still an issue for me on V2.0.0  Many of us feel this would be insanely useful when implemented.

**Comment by clively** [comment]
> Still an issue for me on V2.0.0 Many of us feel this would be insanely useful when implemented.

FYI - it appears to be fixed in the latest beta.

**Comment by clively** [comment]
Fixed in latest beta

**Comment by clively** [comment]
Ugh trying to close…

**Comment by Gozania** [comment]
Before implemented into RC or into the official release, can it be confirmed that filiment choices in the ams would include user filiaments that arent only limited to bambu machines?

I imported my extensive filament collection via a perl script.  Upon doing that it, it made the filaments compatible with all printers & not only bambu.
![filaments](https://github.com/SoftFever/OrcaSlicer/assets/83924000/a0b5439d-5cc6-4a47-8df6-59f426ef0583)

**Comment by Blawlz** [comment]
> Fixed in latest beta

I'm now on v2.1.0beta and have no visibility to my custom / user preset filaments in the AMS device screen. Did you have to do anything to update the previous filaments? Or did they just appear again after an update for you?

**Comment by Daredevll** [comment]
Seems like this was fixed at some point but I am now facing the same issue with 2.2.0-beta. All my custom filaments are not available for selection on the Device tab when setting filament for the AMS. This used to work as expected in previous versions

**Comment by bergie5737** [comment]
I've created a custom filament yesterday, today I can't see it. In the device, I was able to see my custom filament just yesterday, but after loading a previous project this morning, it has dissapeared, and even going back to the project that used the custom filament, it won't come back. I tried restart, connect and disconnect from cloud. Nothing.

I can still select any of my older custom filaments in the device, but not the new one I created, although I can pick it in the filament selection. Somehow either the old profile overwrite the new custom filament, or something weird is happening in the background that saves my settings.

To add further context, I printed a few calibration tests yesterday with the new filament, then a few prints with the new filament, and it all worked as expected until I reloaded a previous project that had different filaments. (Same color, different brand)

**Comment by sandervandenberg** [comment]
Just installed Orca 2.2.0 for the first time and noticed the missing custom filaments that are in my AMS. So this is still an issue.
Hopefully @clively can reopen this issue?

**Comment by clively** [comment]
It wont let me reopen.

**Comment by n3ix** [comment]
Oh well.  Since you had such nice documentation, maybe you could repost as a new issue?

**Comment by billylindeman** [comment]
+1 I just updated to 2.3 beta and this started happening for me.  I can't even see Generic PETG in the dropdown even though it shows up in the slicer.  Very frustrating

**Comment by slikts** [comment]
Seeing this as well, I have several custom filaments defined, but the AMS dropdown shows just one.

**Comment by caprella** [comment]
Orca is updated up to 2.3.0-beta, but issue is still here. There is no any custom filament in AMS dropdowns

**Comment by clively** [comment]
I haven’t had this problem since the issue was closed.  I wonder if you
might just need to recreate the custom filament?

**Comment by caprella** [comment]
> I haven’t had this problem since the issue was closed.  I wonder if you
> might just need to recreate the custom filament?
> […](#)

In fact current custom filament has been created after update up to 2.3.0-beta. Does it still make sense to recreate filament?

**Comment by goldsoundz80** [comment]
I think I might be able to solve this since I encountered the same problem, what I've discovered is that there are two ways to create a custom filament profile and only one of them results in the profile being added to the list in the AMS.

Method 1 (not added to list):
Click this icon next to a filament in the Prepare tab, edit the filament then save it under a different name (ie, create a filament profile based on an existing one)
<img width="408" alt="Image" src="https://github.com/user-attachments/assets/9afed795-1917-4d3d-ada9-a67b1ecbec11" />

Method 2 (added to AMS list)
Click this icon in the Prepare tab, then Custom Filaments > Add New
<img width="423" alt="Image" src="https://github.com/user-attachments/assets/753f2d17-3c4c-418d-b5e6-28ef4c8111f6" />

For the latter method, it'll ask you what printer/nozzle you would like to associate the profile with, where as in Method 1 it doesn't ask this.

I am running my P1S in LAN Mode, if that helps.

**Comment by bergie5737** [comment]
I'm personally aware of these two ways of adding filament. AFAIK this is how its always been. Not sure if it is a feature or a bug, but confusing either way.

**Comment by stevvie** [comment]
> I think I might be able to solve this since I encountered the same problem, what I've discovered is that there are two ways to create a custom filament profile and only one of them results in the profile being added to the list in the AMS.
> 
> Method 1 (not added to list): Click this icon next to a filament in the Prepare tab, edit the filament then save it under a different name (ie, create a filament profile based on an existing one) <img alt="Image" width="408" src="https://private-user-images.githubusercontent.com/23124163/425068694-9afed795-1917-4d3d-ada9-a67b1ecbec11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2MDc4NDMsIm5iZiI6MTc0MzYwNzU0MywicGF0aCI6Ii8yMzEyNDE2My80MjUwNjg2OTQtOWFmZWQ3OTUtMTkxNy00ZDNkLWFkYTktYTY3YjFlY2JlYzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAyVDE1MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNTc5YmQyYWUxM2Q3MTRkMWVjMzk1MDcyZjRlZDliOTE4M2Y4ODk2NDAzNzliMGNhNzMyMDVmYjEwMzJjYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8cpiNI6ZpfXcOH1AIZVDY4NyPH3Uc0MK52v7qgjGnJ0">
> 
> Method 2 (added to AMS list) Click this icon in the Prepare tab, then Custom Filaments > Add New <img alt="Image" width="423" src="https://private-user-images.githubusercontent.com/23124163/425069756-753f2d17-3c4c-418d-b5e6-28ef4c8111f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2MDc4NDMsIm5iZiI6MTc0MzYwNzU0MywicGF0aCI6Ii8yMzEyNDE2My80MjUwNjk3NTYtNzUzZjJkMTctM2M0Yy00MThkLWI1ZTYtMjhlZjRjODExMWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAyVDE1MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDg1ZDYxMmFjNmY5ZWFlNjE1MmRkNmZhNjRhNWE0ZDJjMTcwZDZkYjI1YjhjYjQzMWNkZDNjODAzMjE2NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9ebQKsKi56-eRVfodNHqRjHMD1yQbQUVh1xNDVF7RJ4">
> 
> For the latter method, it'll ask you what printer/nozzle you would like to associate the profile with, whereas in Method 1 it doesn't ask this.
> 
> I am running my P1S in LAN Mode, if that helps.

Thanks for that the only way they show up in the device tab is method 2 for me, but at least creating a custom filament using method 2 you can import it from method 1. How confusing

**Comment by kbuggenhout** [comment]
created a custom filament, and still have ? in the AMS slots when sending to the printer from Orca 3.2-beta ( installed from nightly build on 20 june 2025), while in bambu studio all works as expected and can select my non BBL filament. while orca allows me to select them in prepare, but at send time it refuses.

**Comment by sstickel** [comment]
Well, to me this is still an issue. But maybe I have found the reason for some filaments not showing up, while others work.

At least it works on my machine. ;)

User @Gozania pointed me into a direction with his comment. The filament profile I wanted to use was set to "All" under Dependencies -> Compatible printers. 

Immediately after I unchecked the "All" checkbox and manually selected the profiles I regularly use, the filament showed up in the Device/AMS section.

Hope this helps.

/edit: I just confirmed this behaviour with another filament that was not showing up in the AMS. After doing the change in the dependencies that one also showed up in the AMS.

**Comment by Gozania** [comment]
> Well, to me this is still an issue. But maybe I have found the reason for some filaments not showing up, while others work.
> 
> At least it works on my machine. ;)
> 
> User [@Gozania](https://github.com/Gozania) pointed me into a direction with his comment. The filament profile I wanted to use was set to "All" under Dependencies -> Compatible printers.
> 
> Immediately after I unchecked the "All" checkbox and manually selected the profiles I regularly use, the filament showed up in the Device/AMS section.
> 
> Hope this helps.
> 
> /edit: I just confirmed this behaviour with another filament that was not showing up in the AMS. After doing the change in the dependencies that one also showed up in the AMS.

Glad I was able to help ya out and steer ya in the right direction.
