### ISSUE TITLE
Seam strange behaviour (diagonal)

### ISSUE THREAD

**Issue by streetgt** [SoftFever/OrcaSlicer#4491]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

Tested on 2.0.0 Beta, nightly and stable branch (1.9.1).

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

Not revelant for this issue

### Printer

Not revelant for this issue

### How to reproduce

1 - Add an object in the build plate with the following settings (aligned), as you can see the seam is vertical.
![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/483ee7bc-b39e-4332-9105-b134c8bb23b6)

2- Use the "clone" feature or copy/paste and check now the seam, the seam is on diagonal.
![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/d1a18ecc-abab-41bf-93e9-ad9e96f53501)

3- If you remove the cloned object the issue still, the only way to fix it is closing the software and opening it again.

### Actual results

Seam is on diagonal.

### Expected results

Seam must be vertical.

### Project file & Debug log uploads

Logs not needed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

No

**Comment by streetgt** [comment]
So I wentfurther and tested with a file .3mf and .step. The issue only happens with .step file. I have attached both. It's important to fix this issue because .step is also highly used!

![image](https://github.com/SoftFever/OrcaSlicer/assets/6529821/b80589e9-8b66-4e54-8732-64744cb7066c)


[Test files.zip](https://github.com/SoftFever/OrcaSlicer/files/14727481/Test.files.zip)

**Comment by qocaier** [comment]
I have the same problem. I too think that it's very big bug and it's important to solve them.

**Comment by streetgt** [comment]
> I have the same problem. I too think that it's very big bug and it's important to solve them.

Yes, initially I tought it was related with Scarf seam but it isn't. Should be fixed.

**Comment by GcodeGearHead** [comment]
This is still an issue with step files

<img width="965" height="254" alt="Image" src="https://github.com/user-attachments/assets/9d1e4480-a52b-40cf-8fd7-f224d5a5f90d" />
