### ISSUE TITLE
The 3mf's version 2.0.0.0-dev is newer than Orca Slicer's version 2.0.0.0-beta. Found following keys unrecognised.

### ISSUE THREAD

**Issue by mfraser** [SoftFever/OrcaSlicer#4519]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0.0

### Operating System (OS)

Linux

### OS Version

Kubuntu 22.04

### Printer

Creality K1 Max

### How to reproduce

Load .3mf file created in 2.0.0.0-dev

### Actual results

Get an error saying that Orca Slicer is older than the version used to create the file.

### Expected results

Orca Slicer should know that 2.0.0.0-beta is newer than 2.0.0.0-dev

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

![Screenshot_20240316_183042](https://github.com/SoftFever/OrcaSlicer/assets/195323/6e52682a-a104-45cb-8314-c29bcf10a1c4)

**Comment by SoftFever** [comment]
Thanks.
This is now fixed in latest nightly build

**Comment by J-Dawggg** [comment]
I still get the same error with different version values - I'm running the latest stable build, but constantly get this error when opening a project:  

"The 3mf's version 2.4.0.70 is newer than Orca Slicer's version 2.3.0.1, found following unrecognized keys:
You should update your software."

**Comment by mfraser** [comment]
> I still get the same error with different version values - I'm running the latest stable build, but constantly get this error when opening a project:
> 
> "The 3mf's version 2.4.0.70 is newer than Orca Slicer's version 2.3.0.1, found following unrecognized keys: You should update your software."

Was the 3mf created using BambuStudio instead as that is at version 2.4.0?

**Comment by mfraser** [comment]
Getting this again with 2.3.2-dev. Using the dev version as rc2 got rid of the filename in the title bar.

<img width="890" height="202" alt="Image" src="https://github.com/user-attachments/assets/0ea30e2e-064b-4b77-8b61-b8f57a0bbead" />

**Comment by LJKraus** [comment]
Orca v2.3.2-rc2 was released two weeks ago. 
All the nightly releases identify as v2.3.2-dev.   

I believe the .3mf creation version is compared to the current software version, and 2.3.2-rc2 is considered "newer" because alphanumerically it comes after 2.3.2-dev.

Note that there are actually no unrecognized keys, so the extra "OK" click is only a minor nuisance, but perhaps the warning could be suppressed if there are no unrecognized keys?  That might also be a good idea if all keys from a numerically newer version of Studio are recognized.
