### ISSUE TITLE
Objects not printing correctly when using different filaments.

### ISSUE THREAD

**Issue by richard-scott** [SoftFever/OrcaSlicer#5821]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0

### Operating System (OS)

macOS

### OS Version

Sonoma 14.5

### Additional system information

I have a Mac mini M1 2020.

### Printer

Bambu X1C with AMS

### How to reproduce

I have a medal made of two objects: the face plate and the outer ring. I selected different filaments for each object, and it looks okay in the slicer, but when you print it, the top layers all take the colour of the face plate and do not change for the outer ring. This only happens on the top layers; the bottom layers print fine.

### Actual results

In v2.1.0, I get this:

<img width="1075" alt="Screenshot 2024-06-23 at 10 55 14" src="https://github.com/SoftFever/OrcaSlicer/assets/5149834/c2fa7861-91b4-4ca4-9b2b-51f9acd6d19a">,

### Expected results

In v2.0.0, I get this:
<img width="1075" alt="Screenshot 2024-06-23 at 10 58 00" src="https://github.com/SoftFever/OrcaSlicer/assets/5149834/babe5c30-c2e7-4a4a-b17f-a2462de6e0b5">

### Project file & Debug log uploads

[Medal.3mf.zip](https://github.com/user-attachments/files/15944070/Medal.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Latest Mac build should solve the non shrinkage related MMU issue. Download from the nightly and use this command to "sign" it so it opens.

`xattr -dr com.apple.quarantine /Applications/OrcaSlicer.app`

**Comment by richard-scott** [comment]
@ianalexis It's still the same in the latest build from [here](https://github.com/SoftFever/OrcaSlicer/actions/runs/9665273126).

**Comment by richard-scott** [comment]
This is still the same in v2.1.1 but was working back in v2.0.0.

**Comment by richard-scott** [comment]
The green centre and the orange outer ring are separate objects that are not painted but coloured by selecting different filaments from the AMS.

**Comment by richard-scott** [comment]
This looks to be working now with [v2.2.0-beta](https://github.com/SoftFever/OrcaSlicer/actions/runs/10840202908).
