### ISSUE TITLE
Fuzzy Skin is not random

### ISSUE THREAD

**Issue by Robsbiche** [SoftFever/OrcaSlicer#6228]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

BambuLab X1E

### How to reproduce

Apply fuzzy skin only on a layer range (my case 2mm to 9.5mm)
Set the fuzzy skin setting to outer perimeter only, 0.2 distance and 0.2 thickness

### Actual results

![image](https://github.com/user-attachments/assets/566529f3-d995-4b8a-bfe7-4dd706329219)

### Expected results

The fuzzy skin displays a repetitive pattern instead of a random fuzzy surface

### Project file & Debug log uploads

[Fuzzy skin issue.zip](https://github.com/user-attachments/files/16350323/Fuzzy.skin.issue.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by L2on1** [comment]
I thought it was fixed #5682

**Comment by Robsbiche** [comment]
> I thought it was fixed #5682

It seems like it was, but the problem is still existing in my case.
Maybe because I only apply fuzzy skin on a selective layer height range.

**Comment by discip** [comment]
@Robsbiche
Your project with the latest build:
![image](https://github.com/user-attachments/assets/e07d38f6-bf46-46d3-b07b-fa1c2ab7a152)
🤷‍♂️

**Comment by Robsbiche** [comment]
> @Robsbiche Your project with the latest build: ![image](https://private-user-images.githubusercontent.com/53649486/352523132-e07d38f6-bf46-46d3-b07b-fa1c2ab7a152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTg1NzEsIm5iZiI6MTcyMTk5ODI3MSwicGF0aCI6Ii81MzY0OTQ4Ni8zNTI1MjMxMzItZTA3ZDM4ZjYtYmY0Ni00NmQzLWIwN2ItZmExYzJhYjdhMTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEyNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZGM5MzhmM2UwNDI3ODZiZTQxNjc2OTI5YWU2ZjdlZDAxMjRlOTlmMTgxMjE3YTc5NTdhYjVmZDdiMjIwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._WHP5EpL2OqJozNNyFv9K5Hn6UkLy4lX4-n3oFEUIa4) 🤷‍♂️

Well it's even weirder then.
I use the 2.1.1, isn't it the latest build?

**Comment by Noisyfox** [comment]
Arachne is still broken. The PR #5682 only fixes for classic mode.

**Comment by Noisyfox** [comment]
> @Robsbiche Your project with the latest build: ![image](https://private-user-images.githubusercontent.com/53649486/352523132-e07d38f6-bf46-46d3-b07b-fa1c2ab7a152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNjgyNjcsIm5iZiI6MTcyNjM2Nzk2NywicGF0aCI6Ii81MzY0OTQ4Ni8zNTI1MjMxMzItZTA3ZDM4ZjYtYmY0Ni00NmQzLWIwN2ItZmExYzJhYjdhMTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDAyMzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODJmYzY0ZGNjY2Q1OTdmNmQxODQ5ZTExOWJkMjQ4MzAzODZjZWM5MTJiY2E1ZGEwYjQzNTdiZGVhYWNiNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tf40ARHbIoy6u_lRgpUZ1Twd6njlapZKgOYiTTJGa6Q) 🤷‍♂️

This bug mostly affects Windows user, due to how the `rand()` function is implemented in MSVC.
