### ISSUE TITLE
Prime tower grew very large after slicing

### ISSUE THREAD

**Issue by goombah88** [SoftFever/OrcaSlicer#6760]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

OrcaSlicer_Linux_Ubuntu2404_V2.2.0-beta

### Operating System (OS)

Linux

### OS Version

EndeavourOS (arch linux)

### Additional system information

CPU: AMD Ryzen 9 7950X 16-Core
MEM: 32 GB
Video Card: AMD Radeon RX 7900 XTX

### Printer

Bambu P1S

### How to reproduce

I added a cylinder to the build plate.
Add smaller cylinder centered.
Changed smaller cylinder to a negative part
Sliced

### Actual results

Prime tower grew in the Y direction to go off the top and bottom of the build plate, giving a gcode error as well.

### Expected results

I have my prime tower set to
Width: 35 mm
Prime Volume: 45 mm3
Brim Width: 3 mm

I never change those settings. So the prime tower should not have changed at all when slicing a model. I've never seen this issue before on any previous versions of Orcaslicer. I thought I fixed it by disable/enable the prime tower. That reset the size and put the tower in the lower right corner of the build plate (previously I had it in the upper right corner, if relevant).
But now each time I slice it grows all over again.

### Project file & Debug log uploads

[fan_blades.zip](https://github.com/user-attachments/files/17002556/fan_blades.zip)
[debug_.zip](https://github.com/user-attachments/files/17002569/debug_.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

![image](https://github.com/user-attachments/assets/d97c4ff3-eb39-4670-8054-4fd9d55ac417)

**Comment by goombah88** [comment]
Might be related to https://github.com/SoftFever/OrcaSlicer/issues/6755 but it's hard to be sure since that bug doesn't have much info in it to go on.

**Comment by vgdh** [comment]
Preview size almost always incorrect.
You can make it smaller by decreasing the amount of **prime volume**

**Comment by vgdh** [comment]
Also try to decrease multiplier in **Flushing volume** section

**Comment by goombah88** [comment]
> Also try to decrease multiplier in **Flushing volume** section

I hear ya, but it still has to be a bug with the beta because I have never seen this issue before on any prior version of Orca (or any other slicer for that matter).
![image](https://github.com/user-attachments/assets/c78bb58e-9dcb-40d6-88bd-e8bb8ec629f1)
Again, unchanged from previous versions. Untouched for quite a while actually.

**Comment by SoftFever** [comment]
Thanks.
I can repro it.

Will look into it

**Comment by SoftFever** [comment]
Confirmed it's bug caused by the "Precise Z height" option.
It's not a regression bug in 2.2.0-beta.

For now, please disable it in this option as a workaround.

**Comment by goombah88** [comment]
Confirmed. The workaround removes the issues. Thanks for the quick turnaround. I'll do some more beta testing today.

**Comment by KelsamGames** [comment]
This bug still exists for me whether the Precise Z height option is enabled or not. Prime tower looks right in Prepare, but then generates a huge one when sliced.

**Comment by vanowm** [comment]
Can someone please remove this useless bot, just because there is no activity on an issue, it doesn't make it fixed...(referring to closed by the bot issue)

**Comment by jctune** [comment]
Just noting that I encountered this bug only recently after updating to the 2.3.0-dev released approx. 12/14/25.  Had not encountered this bug previously.

The bug is occurring even though I do not have "Precise Z height" enabled.

**Comment by vgdh** [comment]
> Can someone please remove this useless bot, just because there is no activity on an issue, it doesn't make it fixed...(referring to closed by the bot issues)

Be patient. The purpose of the bot automatically close all not relevant issues. If issue is relevant like this one, people will continue to bump it up.

**Comment by SoftFever** [comment]
Hey guys,

Can you share the sample project if you experienced this issue even though you have the precise Z is not disabled?

**Comment by Apotrox** [comment]
Hey @SoftFever, got one for ya.

![Image](https://github.com/user-attachments/assets/93a65f9e-bc5e-447d-99e1-15a7efdad3b5)

[multimat_issue.zip](https://github.com/user-attachments/files/18469334/multimat_issue.zip)

Also does funny passes at the front?

**Comment by SoftFever** [comment]
This should be fixed in 2.3.0-beta.

**Comment by githomps** [comment]
> This should be fixed in 2.3.0-beta.

Hi @SoftFever, still encountering the same problem. I didn't have Precise Z height enabled when the issue initially presented itself, and enabling it didn't have any impact. 

The issue occurs when using variable layer height after slicing the model. The length of the tower changes depending on the value chosen for the Quality/Speed setting. Applying a 0.5 caused the tower to massively extend in length, easily over a foot. Reducing the value to 0.2 and reslicing caused the tower to shrink to ~6" long, still massive but within the bounds of the build plate. Increasing the value to 0.75 and reslicing returned the tower to its default size. 

I initially encountered the issue in version 2.2.0 attempting to slice a file that I had previously printed with prime tower and variable layer height enabled with no problems. I hadn't saved the file before printing the first time, and Orca crashed, losing my updates. I attempted to re add the models and update my support settings, when the bug presented itself. I updated to the beta version 2.3.0, and tried making a new project using the same model, but the problem persisted. 

Screenshots below after slicing at Variable Layer Height Quality/Speed setting 0.5, reslicing at 0.2, again at 0.75, and then after resetting Variable Layer Height. I also attached the project file.

0.5
![Image](https://github.com/user-attachments/assets/fc93ebd2-d6a2-4796-925d-66424efdd21b)
0.2
![Image](https://github.com/user-attachments/assets/0b726f95-aa0c-46a4-8acf-e5eb9b32e174)
0.75
![Image](https://github.com/user-attachments/assets/91526c86-a359-4861-8d30-521bba906b8c)
Reset
![Image](https://github.com/user-attachments/assets/4221a757-b716-4b98-b41d-88bc2f3610d8)

[Prime Tower Issue File.zip](https://github.com/user-attachments/files/18980553/Prime.Tower.Issue.File.zip)

**Comment by Aggrajag68** [comment]
I still see this problem with 2.3.0 release build 70931e5. It's easy to reproduce:
1) Start a new project.
2) Add any model (I used Benchy).
3) Enable Prime Tower.
4) Click Slice Plate and all is well and good. No tower required.
5) Move the layer slicer down to e.g. slice 174.
6) Add Filament change and re-slice.
7) Looks good but there's a pretty huge tower, no need to waste so much.
8) Change tower Width to 10 (which seems reasonable) and re-slice.
9) Tower extends way off the table.
10) There is no volume option visible (although it appears in the search) so this is not changeable.

**Comment by jamesche75** [comment]
I can confirm this issue still happens in 2.3.0, Build 70931e5. If I disable Precise Z Height, the issue goes away. However, I do see that some people report this even when that option is disabled, so there may be multiple issues here. 

By the way, I have been using Precise Z on this project since installing 2.3.0 without issue. The problem suddenly popped up today with no changes I'm aware of.

**Comment by zoran-grujic** [comment]
In my 2.3.0 Build 70931e5  the bug persists regardless on Precise Z Height or Precise wall. For the first few slice occasions it was OK, and now every new slicing the prime tower is huge in size. I manege to make it reasonable by setting Flushing volumes as @goombah88 suggested. 

![Image](https://github.com/user-attachments/assets/74f526db-62b9-4aea-b8a3-b1a90d35f962)

**Comment by N3rd7** [comment]
Experiencing the same issue! Deselecting precise z-height solve my problem. Strangely it is also new, ie I have done multicolour printing a few days ago without such issue at all. And today, without making any change (that I am aware of), I get a prime tower with gigantic first layers. At maybe 10 or 15% of the prime tower height, it becomes normal size again.

**Comment by zoran-grujic** [comment]
The bug persists in v. 2.3.1
It happens when changing filament type of a part of assembly. Then I have to edit "Flushing volumes" in order to continue.

**Comment by brianleb** [comment]
Hello, this bug has been driving me nuts for a while. I discovered that, in 2.3.1, there is an alert about the interaction. The problem is that if you have prime tower enabled, enabling precise height doesn't trigger the warning; the alert only triggers if you have precise height on and then turn on prime tower. I think it would help a lot of folks if this alert triggered in both directions (assuming it hasn't been fixed for the next version). Thanks!

**Comment by HayatoTenryuu** [comment]
@SoftFever  Problem persists, except in my case, the preview is huge and the sliced version is tiny in comparison. This is an issue because when sliced, it ends up off the plate, and because the preview is gigantic, I can't move it around to fix that.

Using PETG with PLA supports, so I need a lot flushed. The flushing volume section is already maxed, so I have to use a relatively big tower to compensate. The sliced version is the size I need to flush enough, so the actual issue is the gigantic preview. and/or the automatic snapping of the preview.

<img width="3124" height="1635" alt="Image" src="https://github.com/user-attachments/assets/54d36ae2-389a-46e7-92b3-12d2690e431d" /> 

<img width="2632" height="1322" alt="Image" src="https://github.com/user-attachments/assets/6cc8d14e-2786-4f7c-b2d4-b221ad94f8cc" />

<img width="2745" height="1561" alt="Image" src="https://github.com/user-attachments/assets/e1e9fa41-a592-48eb-b5f2-b53928679f2b" />

<img width="2827" height="1588" alt="Image" src="https://github.com/user-attachments/assets/3a5cf870-9151-460d-89e5-40445c61a171" />

**Comment by Unfixingleaf353** [comment]
I HAVE FOUND A SOLUTION

When I downloaded Orca, I got it during the time of this bug, then it updated to versions in which the bug should have been fixed. HOWEVER, it did not fix the bug for me. In order to receive the fix, I had to change my printer present by editing one of the system presets to match my original one that was created before the bug was fixed. It seems like old printer presets do not receive the bug fix and need to be replaced with a newer one. (Works as of version 2.4.0)
