### ISSUE TITLE
Generic PLA shows as ABS

### ISSUE THREAD

**Issue by soundtkllc** [SoftFever/OrcaSlicer#7292]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

All Bambu

### How to reproduce

When you set the filament type in the printer (x1c only) or in the slicer to generic pla it always shows it as ABS. you have to set the type to bambu basic pla to get around this

### Actual results

When you set the filament type in the printer (x1c only) or in the slicer to generic pla it always shows it as ABS. you have to set the type to bambu basic pla to get around this

### Expected results

it should show as pla not abs

### Project file & Debug log uploads

don't have

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Smerks101** [comment]
This is also occurring on the P1P

**Comment by edgarbs1998** [comment]
Same issue here on an A1. However, for me it does not show ABS but ASA and it is stuck on it, I just can't change to Generic PLA. On Bambu Studio it is fine.

**Comment by soundtkllc** [comment]
Originally I said ABS but after reading another person’s comment I confirmed it is actually ASA and I put incorrect info in original post when I stated it was ABS. Same problem but it shows the filament type loaded as ASA in the slicer device tab, when it is clearly entered as Generic PLA, instead of my above statement that it shows ABS.

**Comment by Smerks101** [comment]
I uninstalled the newest version so I cannot check to confirm but it could very well have been ASA instead of ABS.

**Comment by dartrax** [comment]
Same issue here with ABS instead of PLA. There is a good video showing the behavior in #7432.

**Comment by Smerks101** [comment]
> Same issue here with ABS instead of PLA. There is a good video showing the behavior in #7432.

Ive since given up and went back to Bambu slicer. I posted a message about this in the discord and got grief for not posting it here.

**Comment by dartrax** [comment]
unstale

**Comment by soundtkllc** [comment]
Not stale because the issue has never been fixed or even addressed yet

**Comment by dartrax** [comment]
@soundtkllc This may now be fixed in #4690, can you test it and give feedback there?

**Comment by dartrax** [comment]
may be fixed in #4690

**Comment by Smerks101** [comment]
Not fixed as of most recent beta, it shows as ABS not ASA

**Comment by deadcxap** [comment]
orca slicer 2.3.1, buils f2d10a0 - The problem is not resolved, it is impossible to select the generic PLA for printing, ASA is displayed.
I'm a bit surprised that the problem has persisted for 2 years... is it so difficult to fix?..

**Comment by acotam2** [comment]
Still here on 2.3.2-beta, Generic PLA is shown as ASA, generic PETG is PET. Some other randomly checked filaments seem okay.

**Comment by cpuks** [comment]
Same problem on 2.3.2-beta2 - Generic PLA is ABS in my case

**Comment by Syns369** [comment]
same problem here on 2.3.1 build f2d10a0, generic pla default to abs

**Comment by Syns369** [comment]
Hey ! I reinstalled completely orca and the issue is now fixed for all version I had !

**Comment by SneakyAzWhat** [comment]
Problem persists in 2.4.0 DEV as of today. With a fresh install, going through Filament Selection in the setup wizard I am getting odd results when trying to filter for certain filament profiles. X2D as my selected printer but I've tested and replicated with other printers selected too (such as anycubic in these example screenshots.

1) When I select all of the Anycubic printers and filter for PLA filament + Generic brand, I get results for anycubic filament profiles https://i.imgur.com/2lsjItp.png Then if I add a filter for Anycubic branded filaments we start seeing duplicate filament profiles available https://i.imgur.com/JYx3AZD.png You should also note that 'generic pla' profile that I am searching for isn't appearing just yet..

2) Where is the Generic PLA profile? Well it's under the ABS filament type. I have replicated this with multiple printers selected such as bambu and anycubic. https://i.imgur.com/PVDX1ia.png Selecting Generic ABS as my filter options you can now see the generic PLA filament profiles available for selection.

There is something very wrong with the filtering. A lot of branded PLA for example is showing under ABS, in these screenshots I only have generic selected but if you try searching for PLA for all brands, youll see only a few filament profiles show up. If you instead search for ABS for all brands, youll then get PLA profile results from various brands as seen here: https://i.imgur.com/nEcYcnQ.png

I did a reinstall and replicated as well as a config reset and still was able to replicate the issue.

**Comment by ExPikaPaka** [comment]
Similar root cause with this issue [14248](https://github.com/OrcaSlicer/OrcaSlicer/issues/14248)
Is fixed in [PR-14398](https://github.com/OrcaSlicer/OrcaSlicer/pull/14398)
